const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
// Deliberately synthetic key; never put the seminar answer key in test fixtures.
function fixture(){let now=Date.parse('2026-09-19T02:00:00Z'),locked=false;const key=[0,1,2,3,0],properties=new Map([['TRACKER_ID','fixture'],['QUIZ_KEY_fixture',JSON.stringify(key)]]),cache=new Map();
 const tab=(id,rows)=>({rows,getLastRow:()=>rows.length,getSheetId:()=>id,getRange:(r,c,n=1,w=1)=>({getValues:()=>Array.from({length:n},(_,i)=>rows[r-1+i].slice(c-1,c-1+w))}),appendRow:r=>{assert(locked);rows.push(r.map(v=>typeof v==='string'?v.replace(/^'/,''):v));}});
 const control=tab(1,[['Event ID','State','Result Tab ID'],['fixture','OPEN',3]]),sessions=tab(2,[['Event ID','Email','Start Request','Session ID','Started At']]),results=tab(3,[Array(10).fill('header')]);
 const ctx={HtmlService:{createHtmlOutput:text=>({text,setXFrameOptionsMode(mode){assert.equal(mode,'ALLOWALL');return this;}}),XFrameOptionsMode:{ALLOWALL:'ALLOWALL'}},Date:class extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}},props_:()=>({getProperty:k=>properties.get(k)}),normalizedEmail_:v=>v.trim().toLowerCase(),safeCell_:v=>/^[=+\-@]/.test(v)?"'"+v:v,SITE_ORIGIN:'https://bamedicale.com',SpreadsheetApp:{openById:()=>({getSheetByName:n=>n==='Quiz Control'?control:sessions,getSheetById:()=>results}),flush(){}},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;return true;},releaseLock:()=>locked=false})},Utilities:{getUuid:()=>crypto.randomUUID(),formatDate:(date,tz,format)=>{assert.equal(tz,'Asia/Jakarta');const iso=new Date(date.getTime()+7*3600000).toISOString();return format==='yyyy-MM-dd'?iso.slice(0,10):iso.slice(11,19);}},CacheService:{getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v)})},ContentService:{createTextOutput:text=>({text,setMimeType(){return this}}),MimeType:{JAVASCRIPT:'js'}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/backend.js','utf8'),ctx);
 const base={event_id:'fixture',origin:'https://bamedicale.com',request_id:'a'.repeat(32)},start=(email='test@example.com',start_id='b'.repeat(32))=>ctx.quizRecord_({...base,action:'quiz_start',email,start_id}),submit=(token,answers)=>ctx.quizRecord_({...base,action:'quiz_submit',token,answers});return {ctx,base,key,start,submit,results,sessions,control,advance:n=>now+=n};}
test('all six scores are calculated server-side with WIB results',()=>{for(let count=0;count<=5;count++){const f=fixture(),s=f.start();f.advance(22000);const r=f.submit(s.token,f.key.map((a,i)=>i<count?a:(a+1)%4));assert.equal(r.percentage,count*20);assert.equal(r.correct,count);assert.equal(r.elapsed,22);assert.equal(f.results.rows[1][0],'2026-09-19');assert.equal(f.results.rows[1][1],'09:00:22');}});
test('normalized duplicate email, replay and refresh never create another scored attempt',()=>{const f=fixture(),s=f.start(' Test@Example.com ');f.advance(1000);assert.equal(f.start('test@example.com').token,s.token);assert.equal(f.start('test@example.com','c'.repeat(32)).status,'already_started');const resumed=f.ctx.quizRecord_({...f.base,action:'quiz_resume',token:s.token});assert.equal(resumed.startedAt,s.startedAt);f.submit(s.token,f.key);assert.equal(f.submit(s.token,Array(5).fill(null)).percentage,100);assert.equal(f.start('test@example.com').status,'already_completed');assert.equal(f.results.rows.length,2);assert.equal(f.start('te.st+one@example.com').status,'active');});
test('timeout grace is bounded; late answers cannot score; empty answers count incorrect',()=>{const f=fixture(),s=f.start();f.advance(180000);assert.equal(f.submit(s.token,[null,null,null,null,null]).correct,0);const g=fixture(),t=g.start();g.advance(185001);assert.equal(g.submit(t.token,g.key).correct,0);assert.equal(g.results.rows[1][6],180);});
test('closed start and hostile requests fail safely',()=>{const f=fixture();f.control.rows[1][1]='CLOSED';assert.equal(f.start().status,'closed');assert.equal(f.ctx.quizRecord_({...f.base,action:'quiz_start',email:'x@example.com',start_id:'b'.repeat(32),correct:5}).status,'invalid');f.control.rows[1][1]='OPEN';const s=f.start('=bad@example.com');assert.equal(f.sessions.rows[1][1],'=bad@example.com');assert.equal(f.submit(s.token,[0,0,0,0,9]).status,'invalid');assert.equal(f.ctx.quizRecord_({...f.base,action:'quiz_resume',token:'0'.repeat(64)}).status,'invalid');});
test('leaderboard exposes only masked Top 5 and ranks score/time/timestamp',()=>{const f=fixture();const rows=Array.from({length:8},(_,i)=>['','','player'+i+'@example.com',4,5,80,i===0?30:20,'Completed','private',100-i]);rows[0][5]=100;const top=f.ctx.quizLeaderboard_(rows);assert.equal(top.length,5);assert.equal(top[0].percentage,100);assert.equal(top[1].elapsed,20);assert(top.every(p=>p.email==='pl***@example.com'));assert(!JSON.stringify(top).includes('private'));const ties=f.ctx.quizLeaderboard_([['','','a@example.com',4,5,80,10,'Completed','x',2],['','','b@example.com',4,5,80,10,'Completed','y',1]]);assert.equal(ties[0].email,'b***@example.com');});
test('acknowledgement includes no participant email or answer key; callback is validated',()=>{const f=fixture();assert.equal(f.ctx.quizPost_({...f.base,action:'quiz_start',email:'private@example.com',start_id:'b'.repeat(32)}).text,'Quiz request processed.');const r=f.ctx.quizGet_({...f.base,action:'quiz_ack',callback:'baQuiz_'+f.base.request_id});assert(!r.text.includes('private@example.com'));assert(!r.text.includes('key'));assert.equal(f.ctx.quizGet_({...f.base,action:'quiz_ack',callback:'evil()'}).text,'Request unavailable.');});
