const fs = require("fs");
const path = require("path");

const dir = __dirname;
const root = path.resolve(dir,"../..");
const source = fs.readFileSync(path.join(dir,"backend.js"),"utf8").replace(/^\uFEFF/,"");
const output = `/* Generated from scripts/jumi/backend.js. Do not edit this file directly. */\n${source.trim()}\n`;
const target = path.join(dir,"Code.gs");
const css = fs.readFileSync(path.join(root,"jumi/styles.css"),"utf8");
const client = fs.readFileSync(path.join(root,"jumi/app.js"),"utf8");
const officialLogoPath = "assets/brand/bamedicale-approved-logo.jpg";
if(!fs.existsSync(path.join(root,officialLogoPath))) throw new Error("Canonical BA Medicale logo is missing.");
const shell = fs.readFileSync(path.join(root,"jumi/index.html"),"utf8")
  .replace(/\s*<meta http-equiv="Content-Security-Policy"[^>]+>/i,"")
  .replace('<link rel="stylesheet" href="styles.css">',`<style>${css}</style>`)
  .replace('  <script src="config.js" defer></script>\n',"")
  .replace('  <script src="app.js" defer></script>',`<script>window.JUMI_CONFIG={timezone:"Asia/Jakarta"};window.JUMI_SERVER_MODE=true;</script>\n  <script>${client}</script>`)
  .replaceAll(`../${officialLogoPath}`,`https://bamedicale.com/${officialLogoPath}`);
const htmlTarget = path.join(dir,"Index.html");

if(process.argv.includes("--check")){
  if(!fs.existsSync(target) || fs.readFileSync(target,"utf8")!==output || !fs.existsSync(htmlTarget) || fs.readFileSync(htmlTarget,"utf8")!==shell){
    console.error("JUMI Apps Script bundle is stale. Run npm run jumi:build.");
    process.exit(1);
  }
  console.log("JUMI backend bundle is current.");
}else{
  fs.writeFileSync(target,output);
  fs.writeFileSync(htmlTarget,shell);
  console.log("JUMI backend bundle generated.");
}
