const fs = require("fs");
const path = require("path");

const dir = __dirname;
const root = path.resolve(dir,"../..");
const source = fs.readFileSync(path.join(dir,"backend.js"),"utf8").replace(/^\uFEFF/,"");
const taxonomyContext={window:{}};require("vm").runInNewContext(fs.readFileSync(path.join(root,"content.js"),"utf8"),taxonomyContext);
const videoTaxonomy="/* Generated from the canonical BA Medicale disease taxonomy. */\nvar JUMI_VIDEO_TAXONOMY="+JSON.stringify(taxonomyContext.window.BAMEDICALE_DATA.diseaseTaxonomy.map(({id,name})=>({id,name})))+";\nif(typeof module===\"object\"&&module.exports)module.exports=JUMI_VIDEO_TAXONOMY;\n";
const taxonomyTarget=path.join(root,"jumi/video-taxonomy.js");
const videoContract = fs.readFileSync(path.join(root,"jumi/video-contract.js"),"utf8");
const videoBackend = fs.readFileSync(path.join(dir,"video-backend.js"),"utf8");
const output = `/* Generated from scripts/jumi/backend.js. Do not edit this file directly. */\n${videoContract}\n${videoTaxonomy}\n${source.trim()}\n${videoBackend.trim()}\n`;
const target = path.join(dir,"Code.gs");
const css = fs.readFileSync(path.join(root,"jumi/styles.css"),"utf8");
const scope = fs.readFileSync(path.join(root,"jumi/scope.js"),"utf8");
const contentOs = fs.readFileSync(path.join(root,"jumi/content-os.js"),"utf8");
const videoUi = fs.readFileSync(path.join(root,"jumi/video-ui.js"),"utf8");
const client = fs.readFileSync(path.join(root,"jumi/app.js"),"utf8");
const officialLogoPath = "assets/brand/bamedicale-approved-logo.jpg";
if(!fs.existsSync(path.join(root,officialLogoPath))) throw new Error("Canonical BA Medicale logo is missing.");
const shell = fs.readFileSync(path.join(root,"jumi/index.html"),"utf8")
  .replace(/\s*<meta http-equiv="Content-Security-Policy"[^>]+>/i,"")
  .replace(/<link rel="stylesheet" href="styles\.css[^\"]*">/,()=>`<style>${css}</style>`)
  .replace(/\s*<script src="scope\.js[^"]*" defer><\/script>/,"")
  .replace(/\s*<script src="content-os\.js[^"]*" defer><\/script>/,"")
  .replace(/\s*<script src="video-contract\.js[^"]*" defer><\/script>/,"")
  .replace(/\s*<script src="video-taxonomy\.js[^"]*" defer><\/script>/,"")
  .replace(/\s*<script src="video-ui\.js[^"]*" defer><\/script>/,"")
  .replace(/\s*<script src="config\.js[^"]*" defer><\/script>/,"")
  .replace(/<script src="app\.js[^"]*" defer><\/script>/,()=>`<script>${scope}</script>\n  <script>${contentOs}</script>\n  <script>${videoContract}</script>\n  <script>${videoTaxonomy}</script>\n  <script>${videoUi}</script>\n  <script>window.JUMI_CONFIG={timezone:"Asia/Jakarta"};window.JUMI_SERVER_MODE=true;</script>\n  <script>document.addEventListener("DOMContentLoaded",()=>{${client}});</script>`)
  .replaceAll(`../${officialLogoPath}`,`https://bamedicale.com/${officialLogoPath}`);
const htmlTarget = path.join(dir,"Index.html");

if(process.argv.includes("--check")){
  if(!fs.existsSync(taxonomyTarget)||fs.readFileSync(taxonomyTarget,"utf8")!==videoTaxonomy||!fs.existsSync(target) || fs.readFileSync(target,"utf8")!==output || !fs.existsSync(htmlTarget) || fs.readFileSync(htmlTarget,"utf8")!==shell){
    console.error("JUMI Apps Script bundle is stale. Run npm run jumi:build.");
    process.exit(1);
  }
  console.log("JUMI backend bundle is current.");
}else{
  fs.writeFileSync(taxonomyTarget,videoTaxonomy);
  fs.writeFileSync(target,output);
  fs.writeFileSync(htmlTarget,shell);
  console.log("JUMI backend bundle generated.");
}
