const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),vm=require('vm'),crypto=require('crypto');
const newVideoId="ba-medicale-current-diagnostic-approach-thyroid-nodules-seminar-2026";
const root=path.resolve(__dirname,'../..'),C=require('../../jumi/video-contract'),publisher=require('./apply-publication'),boundary=require('./validate-release-diff'),dashboard=require('../../jumi/content-os');
const originals=JSON.parse(fs.readFileSync(path.join(root,'data/original-videos.json'),'utf8')).videos.filter(v=>!v.publicationId);
const fixtureOriginal=originals.find(v=>v.id==="ba-medicale-clinical-learning-preview"),source=fs.readFileSync(path.join(root,fixtureOriginal.video_url)),poster=fs.readFileSync(path.join(root,fixtureOriginal.thumbnail)),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function metadata(){return{title:'Non-public reviewed fixture',subtitle:'',quickSummary:'Approved fixture description.',source:'Approved source record',sourcePublishedDate:'',tags:['Clinical Education','Thyroid'],publication:{primaryAudience:'Public',audienceReviewed:true,primaryDiseaseGroup:'cancer-neoplastic',primaryTopic:'Clinical Education',contentType:'Video',promotion:{hook:'Approved fixture title',teaser:['Approved fixture description.'],hashtags:['#Education','#Thyroid']}}};}
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jumi-video-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const slug='non-public-fixture',p=C.paths(slug,'jpg');for(const [file,bytes]of[[p.source,source],[p.artwork,poster],['data/original-videos.json',JSON.stringify({videos:originals})]]){fs.mkdirSync(path.dirname(path.join(dir,file)),{recursive:true});fs.writeFileSync(path.join(dir,file),bytes);}const manifest={schemaVersion:1,contentId:'content_abcdefabcdefabcd',contentType:'Video',slug,version:4,baseSha:'1'.repeat(40),requestedAt:'2026-09-22T03:00:00Z',metadata:{...metadata(),publishedDate:'2026-09-22',durationSeconds:C.mp4(source).durationSeconds},assets:{source:{path:p.source,mimeType:'video/mp4',public:true,size:source.length,sha256:hash(source)},artwork:{path:p.artwork,mimeType:'image/jpeg',extension:'jpg',size:poster.length,sha256:hash(poster)}}};const request='data/jumi-publication-requests/'+manifest.contentId+'.json';fs.mkdirSync(path.dirname(path.join(dir,request)),{recursive:true});fs.writeFileSync(path.join(dir,request),JSON.stringify(manifest));return{root:dir,manifest,request};}
function context(){const c={console,Date,Utilities:{formatDate:()=> '2026-09-22T03:00:00Z',getUuid:()=> 'abcdefabcdefabcd',base64Decode:s=>Array.from(Buffer.from(s,'base64')),base64Encode:b=>Buffer.from(b).toString('base64')}};vm.createContext(c);for(const file of['jumi/video-contract.js','jumi/video-taxonomy.js','scripts/jumi/backend.js','scripts/jumi/video-backend.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),c);return c;}
test('MP4 structure, reliable duration and source bytes remain intact',()=>{const before=hash(source),v=C.mp4(source);assert.equal(v.valid,true);assert.equal(v.durationSeconds,10.006);assert.equal(hash(source),before);});
test('invalid, truncated and oversized MP4 fail closed',()=>{for(const bytes of[Buffer.from('not a video'),source.subarray(0,source.length-10),Buffer.alloc(C.MAX_VIDEO+1)])assert.throws(()=>C.mp4(bytes));});
test('Historical Originals poster locks retain their approved 9:16 posters',()=>{for(const v of originals.filter(v=>v.id!==newVideoId))assert.equal(C.poster(fs.readFileSync(path.join(root,v.thumbnail)),'image/jpeg').ratio,9/16);assert.throws(()=>C.poster(poster,'image/webp'));assert.throws(()=>C.poster(Buffer.from('bad'),'image/jpeg'));});
test('landscape PNG dimensions cannot bypass the poster gate',()=>{const b=Buffer.alloc(40);b[0]=137;b.write('PNG',1);b.write('IHDR',12);b.writeUInt32BE(1600,16);b.writeUInt32BE(900,20);assert.throws(()=>C.poster(b,'image/png'),/9:16/);});
test('reviewed metadata retains separate taxonomy, hashtags and optional source date',()=>{const m=C.metadata(metadata());assert.equal(m.sourcePublishedDate,'');assert.equal(m.publication.contentType,'Video');assert.notDeepEqual(m.tags,m.publication.promotion.hashtags);assert.equal(m.author,undefined);assert.equal(m.transcript,undefined);});
test('ambiguous Audience and missing metadata block publication',()=>{for(const change of[m=>m.publication.primaryAudience='Needs Review',m=>m.publication.audienceReviewed=false,m=>m.title='',m=>m.source='',m=>m.tags=[]]){const m=metadata();change(m);assert.throws(()=>C.metadata(m));}});
test('private URLs, markup and token-like values cannot cross public fields',()=>{for(const bad of['https://drive.google.com/file/d/private','<script>alert(1)</script>','github_pat_private'])assert.throws(()=>C.metadata({...metadata(),source:bad}));});
test('server paths reject traversal and unsupported assets',()=>{for(const s of['../evil','a/evil','UPPER','a..b'])assert.throws(()=>C.paths(s,'jpg'));assert.throws(()=>C.paths('valid-slug','svg'));});
test('non-public fixture publishes a catalog record and exact receipt without source changes',t=>{const f=fixture(t),result=publisher.applyPublication(f.root,f.request),catalog=JSON.parse(fs.readFileSync(path.join(f.root,'data/original-videos.json')));assert.deepEqual(catalog.videos.slice(0,originals.length),originals);assert.equal(catalog.videos.length,originals.length+1);assert.equal(result.receipt.publicUrl,'https://bamedicale.com/videos.html?video=non-public-fixture');assert.equal(hash(fs.readFileSync(path.join(f.root,result.paths.source))),hash(source));assert.doesNotMatch(JSON.stringify(result.record),/drive\.google|admin|audit|credentials/i);});
test('integrity failure retains previous catalog and request for retry',t=>{const f=fixture(t),before=fs.readFileSync(path.join(f.root,'data/original-videos.json'));fs.appendFileSync(path.join(f.root,f.manifest.assets.source.path),'changed');assert.throws(()=>publisher.applyPublication(f.root,f.request),/integrity/);assert.deepEqual(fs.readFileSync(path.join(f.root,'data/original-videos.json')),before);assert.ok(fs.existsSync(path.join(f.root,f.request)));});
test('private additional fields and fabricated duration are rejected',t=>{const f=fixture(t);f.manifest.metadata.driveId='private';assert.throws(()=>publisher.validateManifest(f.manifest,f.root),/Unexpected/);delete f.manifest.metadata.driveId;f.manifest.metadata.durationSeconds=99;assert.throws(()=>publisher.validateManifest(f.manifest,f.root),/duration/);});
test('historical Originals cannot be overwritten by a new draft',t=>{const f=fixture(t),catalog=JSON.parse(fs.readFileSync(path.join(f.root,'data/original-videos.json')));catalog.videos.push({...originals[0],id:f.manifest.slug,video_url:f.manifest.assets.source.path});fs.writeFileSync(path.join(f.root,'data/original-videos.json'),JSON.stringify(catalog));assert.throws(()=>publisher.validateManifest(f.manifest,f.root),/Duplicate/);});
test('independent metadata replacement preserves identity and catalog position',t=>{const f=fixture(t);publisher.applyPublication(f.root,f.request);f.manifest.version++;f.manifest.metadata.title='Approved correction';fs.writeFileSync(path.join(f.root,f.request),JSON.stringify(f.manifest));const r=publisher.applyPublication(f.root,f.request);assert.equal(r.record.title,'Approved correction');assert.equal(r.record.id,f.manifest.slug);assert.equal(JSON.parse(fs.readFileSync(path.join(f.root,'data/original-videos.json'))).videos.length,originals.length+1);});
test('Video release boundary excludes YouTube, scripts and unrelated private files',t=>{const f=fixture(t);for(const file of['data/videos.json','jumi/config.js','Material/video.mp4','.github/workflows/evil.yml','assets/videos/other.mp4'])assert.throws(()=>boundary.validate(f.manifest,[file]));assert.equal(boundary.validate(f.manifest,['data/original-videos.json',f.manifest.assets.source.path]),true);});
test('server draft strips arbitrary input and uses normalized tags',()=>{const c=context(),m=metadata(),r=c.jumiVideoValue_({type:'Video',title:m.title,quickSummary:m.quickSummary,source:m.source,primaryAudience:'Public',audienceReviewed:'Reviewed',primaryDiseaseGroup:'cancer-neoplastic',primaryTopic:'Education',tags:'thyroid, Thyroid, ultrasound',arbitraryHtml:'<script>'},{email:'qa@example.invalid'});assert.equal(r.Status,'Draft');assert.doesNotMatch(r['Type Data JSON'],/arbitraryHtml|<script>/);assert.equal(JSON.parse(r['Type Data JSON']).publication.audienceReviewed,true);});
test('Video cannot validate without generated, hashed private assets',()=>{const c=context(),r={type:'Video',title:metadata().title,slug:'test-video',typeData:metadata(),sourceStored:false,artworkStored:false};assert.ok(c.jumiContentIssues_(r).some(x=>x.includes('MP4')));assert.ok(c.jumiContentIssues_(r).some(x=>x.includes('Generate')));});
test('Video API preserves unauthorized-account denial',()=>{const c=context();c.jumiAuthorize_=()=>{throw Error('Denied');};assert.throws(()=>c.jumiApi('jumi_generate_video',{}),/Denied/);assert.throws(()=>c.jumiApi('jumi_preview_video',{}),/Denied/);});
test('Control Tower recognizes Videos without imposing a weekly cadence',()=>{const r=dashboard.dashboard({content:[{id:'v',type:'Video',title:'Approved original',status:'Published',publishedAt:'2026-09-22'}],events:[]},Date.parse('2026-09-22T12:00:00+07:00'),'Videos');assert.equal(r.summary.published,1);assert.equal(r.mix.find(x=>x.label==='Video').count,1);assert.equal(r.summary.velocity,0.2);assert.ok(r.calendar.some(x=>x.type==='Video'));assert.equal(r.summary.needsReview,0);});
test('VideoObject metadata uses only known dates and durations, without changing social logo',()=>{const schema=require('../build-original-video-metadata').schema([{...originals[0],publishedDate:'',durationSeconds:undefined}])['@graph'][0];assert.equal(schema.uploadDate,undefined);assert.equal(schema.duration,undefined);assert.match(schema.publisher.logo.url,/bamedicale-approved-logo/);});
test('existing Originals player and YouTube collection remain separate native/embedded paths',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');assert.match(app,/openLocalVideo/);assert.match(app,/data-video-local/);assert.match(app,/video_url/);assert.match(app,/youtube-nocookie/);assert.ok(originals.length >= 1);});

test('Video Intelligent BAU requires only MP4 and generates the locked poster from a source frame',()=>{
  const app=fs.readFileSync(path.join(root,'jumi/app.js'),'utf8'),ui=fs.readFileSync(path.join(root,'jumi/video-ui.js'),'utf8');
  assert.match(ui,/Upload one approved MP4/);assert.doesNotMatch(ui,/data-content-file="artwork"/);assert.match(ui,/Analyze Video & Generate/);assert.match(ui,/Choose another frame/);
  assert.match(app,/function videoEvidence/);assert.match(app,/primaryAudience=.*Healthcare Professionals/);assert.match(app,/function videoPosterFile/);assert.match(app,/canvas\.width=width/);assert.match(app,/drawImage\(video/);assert.match(app,/width:1080,height:1920/);assert.match(app,/fileName:item\.file\.name/);
  assert.match(fs.readFileSync(path.join(__dirname,'video-backend.js'),'utf8'),/Source metadata extracted — Review Required/);
});

function operational(){
  const c=context(),m=metadata(),admin={email:'qa@example.invalid'},audit=[],files=new Map();let row=c.jumiVideoValue_({type:'Video',title:m.title,slug:'non-public-fixture',quickSummary:m.quickSummary,source:m.source,primaryAudience:'Public',audienceReviewed:'Reviewed',primaryDiseaseGroup:'cancer-neoplastic',primaryTopic:'Clinical Education',tags:m.tags.join(',')},admin);row._row=2;
  const blob=(bytes,mime)=>({getBytes:()=>Array.from(bytes),getContentType:()=>mime,setName(){return this;}});
  c.Utilities.newBlob=(bytes,mime)=>blob(Buffer.from(bytes),mime);c.jumiSha256_=b=>hash(Buffer.from(b.getBytes()));c.jumiSs_=()=>({});c.jumiTab_=()=>({});c.jumiContentRows_=()=>[row];c.jumiObjects_=()=>[row];c.jumiUpdateRow_=(_s,_r,_h,value)=>{row={...value,_row:2};};c.jumiAudit_=(...args)=>audit.push(args);
  c.jumiContentFolder_=()=>({createFile(b){const id='private-'+files.size,f={getId:()=>id,getMimeType:()=>b.getContentType(),getBlob:()=>b,getSharingAccess:()=> 'PRIVATE'};files.set(id,f);return f;}});c.DriveApp={Access:{PRIVATE:'PRIVATE'},getFileById:id=>{assert.ok(files.has(id));return files.get(id);}};c.LockService={getScriptLock:()=>({waitLock(){},releaseLock(){}})};
  return{c,admin,audit,files,row:()=>row,upload(){c.jumiUploadContentAsset_({contentId:row['Content ID'],kind:'source',mimeType:'video/mp4',base64:source.toString('base64')},admin);c.jumiUploadContentAsset_({contentId:row['Content ID'],kind:'artwork',mimeType:'image/jpeg',base64:poster.toString('base64')},admin);}};
}
test('private Upload → Generate → Validate → playable Preview → contract is operational',t=>{
  const o=operational();o.upload();const id=o.row()['Content ID'];o.c.jumiGenerateVideo_({contentId:id},o.admin);assert.equal(o.row().Status,'Generated');assert.equal(o.c.jumiValidateContent_({contentId:id},o.admin).valid,true);
  assert.throws(()=>o.c.jumiRecordContentPreview_({contentId:id},o.admin),/playable/);
  const preview=o.c.jumiPreviewVideo_({contentId:id},o.admin);assert.equal(hash(Buffer.from(preview.videoBase64,'base64')),hash(source));assert.doesNotMatch(JSON.stringify(preview),/private-|drive\.google/);
  o.c.jumiRecordContentPreview_({contentId:id},o.admin);assert.equal(o.row().Status,'Ready to Publish');
  const release=o.c.jumiPublicationManifest_(o.row(),'1'.repeat(40)),f=fixture(t);f.manifest=JSON.parse(JSON.stringify(release.manifest));fs.writeFileSync(path.join(f.root,f.request),JSON.stringify(f.manifest));const result=publisher.applyPublication(f.root,f.request);assert.equal(result.record.id,'non-public-fixture');assert.equal(o.row().Status,'Ready to Publish','Repository preparation never marks the live private row Published');assert.ok(o.audit.length>=5);
});
test('missing storage and stored hash changes fail without generating or publishing',()=>{
  const o=operational();o.c.jumiContentFolder_=()=>{throw Error('Private Content Sources folder is not configured.');};assert.throws(()=>o.upload(),/not configured/);assert.equal(o.row().Status,'Draft');assert.throws(()=>o.c.jumiGenerateVideo_({contentId:o.row()['Content ID']},o.admin),/MP4/);
});
test('publisher failure records Failed and retains private source for safe retry',()=>{
  const o=operational();o.upload();const id=o.row()['Content ID'];o.c.jumiGenerateVideo_({contentId:id},o.admin);o.c.jumiValidateContent_({contentId:id},o.admin);o.c.jumiPreviewVideo_({contentId:id},o.admin);o.c.jumiRecordContentPreview_({contentId:id},o.admin);
  o.c.jumiProps_=()=>({getProperty:()=>null});o.c.jumiCreateRelease_=()=>{throw Error('Publisher is not configured.');};assert.throws(()=>o.c.jumiPublishContent_({contentId:id},o.admin),/not configured/);assert.equal(o.row().Status,'Failed');assert.ok(o.row()['Source File ID']);assert.equal(o.files.size,2);
});
test('replacement resets generated, validation and preview states and retains prior hash provenance',()=>{
  const o=operational();o.upload();const id=o.row()['Content ID'];o.c.jumiGenerateVideo_({contentId:id},o.admin);o.c.jumiValidateContent_({contentId:id},o.admin);o.c.jumiPreviewVideo_({contentId:id},o.admin);o.c.jumiRecordContentPreview_({contentId:id},o.admin);o.upload();assert.equal(o.row().Status,'Draft');assert.equal(o.row()['Preview State'],'Not Previewed');const d=JSON.parse(o.row()['Type Data JSON']);assert.equal(d.generated,false);assert.ok(d.assetHistory.some(x=>x.sha256===hash(source)));assert.equal(d.previewVersion,undefined);
});
test('repository growth stops before any GitHub write',()=>{
  const c=context(),calls=[];c.jumiGithub_=(method,url)=>{calls.push(method);if(url.startsWith('/git/trees'))return{tree:[{type:'blob',path:'existing',size:C.MAX_TREE}],truncated:false};throw Error('Unexpected network call');};assert.throws(()=>c.jumiVideoRepositoryGuard_({Slug:'new-video'},{manifest:{baseSha:'1'.repeat(40),assets:{source:{path:'assets/videos/new-video.mp4',size:1}}}}),/budget/);assert.deepEqual(calls,['get']);
});
test('source decode adapter requests validation only and rejects unsupported codecs',t=>{const f=fixture(t);
  const cp=require('child_process'),old=cp.execFileSync,calls=[];cp.execFileSync=(bin,args)=>{calls.push([bin,args]);return JSON.stringify({streams:[{codec_type:'video',codec_name:'vp9',pix_fmt:'yuv420p'}]});};try{assert.throws(()=>require('./video-publication').verifyMedia(f.root,f.manifest),/H.264/);cp.execFileSync=(bin,args)=>{calls.push([bin,args]);return JSON.stringify({streams:[{codec_type:'video',codec_name:'h264',pix_fmt:'yuv420p'}]});};assert.equal(require('./video-publication').verifyMedia(f.root,f.manifest),true);assert.equal(calls.filter(x=>x[0]==='ffmpeg').length,2);assert.ok(calls.filter(x=>x[0]==='ffmpeg').every(x=>x[1].slice(-3).join(',')==='-f,null,-'));}finally{cp.execFileSync=old;}
});
function reconciliation(receipt,status='built'){
  const c=context(),data={sourceAsset:{sha256:'a'.repeat(64)},artwork:{sha256:'b'.repeat(64)}},row={'Content ID':'content_abcdefabcdefabcd','Content Type':'Video',Slug:'fixture',Version:4,Status:'Ready to Publish','Preview State':'Previewed','Type Data JSON':JSON.stringify(data),_row:2},calls=[];
  c.jumiGithubConfigured_=()=>true;c.jumiOptionalTab_=()=>({});c.jumiContentRows_=()=>[row];c.jumiProps_=()=>({getProperty:()=>JSON.stringify({version:4,branch:'jumi-publish/content_abcdefabcdefabcd-v4',requestedAt:'2026-09-22T00:00:00Z',pagesRequestedAt:'2026-09-22T01:00:00Z'}),setProperty(){},deleteProperty(){}});c.UrlFetchApp={fetch:url=>String(url).includes('api.github.com')?({getResponseCode:()=>receipt?200:404,getContentText:()=>JSON.stringify({content:Buffer.from(JSON.stringify(receipt)).toString('base64')})}):String(url).includes('jumi-public-catalog')?({getResponseCode:()=>200,getContentText:()=>JSON.stringify({items:[{id:'content_abcdefabcdefabcd',route:'videos.html?video=fixture'}]})}):({getResponseCode:()=>200,getContentText:()=>''})};c.Utilities.newBlob=b=>({getDataAsString:()=>Buffer.from(b).toString()});c.jumiGithub_=(method,url)=>{calls.push(url);if(url.includes('/runs?'))return{workflow_runs:[{created_at:'2026-09-22T02:00:00Z',display_title:'Publish jumi-publish/content_abcdefabcdefabcd-v4',status:'completed',conclusion:'failure'}]};return url.includes('/pages/')?{status,commit:'main-sha',created_at:'2026-09-22T02:00:00Z'}:{object:{sha:'main-sha'}};};c.jumiUpdateRow_=(_s,_r,_h,v)=>Object.assign(row,v);c.jumiAudit_=()=>{};c.jumiSyncPublishedContent_=()=>{};
  return{c,row,calls};
}
test('wrong receipt hashes cannot mark Video Published or request Pages',()=>{const x=reconciliation({contentId:'content_abcdefabcdefabcd',contentType:'Video',slug:'fixture',version:4,sourceSha256:'wrong',artworkSha256:'b'.repeat(64),publicUrl:'https://bamedicale.com/videos.html?video=fixture'});x.c.jumiReconcilePublications_({},{});assert.equal(x.row.Status,'Ready to Publish');assert.equal(x.calls.length,0);});
test('exact receipt still requires successful current Pages build',()=>{const receipt={contentId:'content_abcdefabcdefabcd',contentType:'Video',slug:'fixture',version:4,sourceSha256:'a'.repeat(64),artworkSha256:'b'.repeat(64),publicUrl:'https://bamedicale.com/videos.html?video=fixture',publishedAt:'2026-09-22T00:00:00Z'};for(const [status,expected]of[['building','Ready to Publish'],['built','Published']]){const x=reconciliation(receipt,status);x.c.jumiReconcilePublications_({},{});assert.equal(x.row.Status,expected);}});
test('failed Video release is reconciled by exact workflow run title on main',()=>{const x=reconciliation(null);x.c.jumiReconcilePublications_({},{});assert.equal(x.row.Status,'Failed');assert.ok(x.calls.some(url=>url.includes('branch=main')));});
test('published fixture joins canonical search, audience discovery and related learning',t=>{const f=fixture(t),result=publisher.applyPublication(f.root,f.request),c={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'content.js'),'utf8'),c);const api=require('../../content-registry'),registry=api.create(c.window.BAMEDICALE_DATA,{originalVideos:[...originals,result.record],videos:require('../../data/videos.json').videos});assert.equal(api.validate(registry,c.window.BAMEDICALE_DATA,{root,exists:(base,asset)=>fs.existsSync(path.join(base,asset))||fs.existsSync(path.join(f.root,asset))}),true);const item=registry.byId(result.record.id);assert.equal(item.route,'videos.html?video=non-public-fixture');assert.ok(registry.query({family:'video',audience:'PUBLIC'}).some(x=>x.id===item.id));assert.ok(registry.related(item.id).length>0);assert.match(JSON.stringify(item),/Approved fixture description/);});
test('explicit catalog refresh sees newly published Videos despite the older cache',()=>{const c=context(),old=[{id:'old',type:'Article'}],fresh=[...old,{id:'original',type:'Video'}];let stored=JSON.stringify({items:old}),fetches=0;c.CacheService={getScriptCache:()=>({get:()=>stored,put:(_key,value)=>{stored=value;}})};c.UrlFetchApp={fetch:()=>{fetches++;return{getResponseCode:()=>200,getContentText:()=>JSON.stringify({items:fresh})};}};assert.equal(c.jumiPublicCatalog_(false).length,1);assert.equal(fetches,0);assert.equal(c.jumiPublicCatalog_(true).length,2);assert.equal(fetches,1);assert.equal(c.jumiPublicCatalog_(false).length,2);});
test('catalog refresh failure retains the last valid catalog',()=>{const c=context();c.CacheService={getScriptCache:()=>({get:()=>JSON.stringify({items:[{id:'retained'}]}),put(){throw Error('Must not replace valid cache');}})};for(const fail of[()=>{throw Error('Network failure');},()=>({getResponseCode:()=>503}),()=>({getResponseCode:()=>200,getContentText:()=>'{"unexpected":true}'})]){c.UrlFetchApp={fetch:fail};assert.equal(c.jumiPublicCatalog_(true)[0].id,'retained');}});
