const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(__dirname+'/backend.js','utf8');
function fixture(){
 const properties=new Map(),tabs=new Map();let locked=false,writes=0;
 const c={PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)??null,setProperty:(k,v)=>properties.set(k,v)})},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;return true},releaseLock:()=>{locked=false}})},Utilities:{formatDate:(_d,tz,fmt)=>{assert.equal(tz,'Asia/Jakarta');return fmt==='yyyy-MM-dd'?'2026-09-19':'09:00:00'}},SpreadsheetApp:{openById:()=>({getSheetById:id=>tabs.get(id)}),flush:()=>{}},HtmlService:{createHtmlOutput:text=>({text,setXFrameOptionsMode(){return this}}),XFrameOptionsMode:{ALLOWALL:'ALLOWALL'}}};
 vm.createContext(c);vm.runInContext(source,c);c.safeCell_=vm.runInContext('safeCell_',c);
 const headers=vm.runInContext('ATTENDANCE_HEADERS',c);
 function tab(id,rows){const t={rows,getLastRow:()=>rows.length,getMaxRows:()=>1000,getRange:(r,col,n=1,w=1)=>({getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>rows[r-1+i]?.[col-1+j]??'')),setNumberFormat(){return this},setValues(values){assert(locked,'writes must be locked');writes++;values.forEach((row,i)=>{rows[r-1+i]??=[];row.forEach((v,j)=>{rows[r-1+i][col-1+j]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v})});return this}})};tabs.set(id,t);return t}
 properties.set('TRACKER_ID','fixture');properties.set('EVENTS_TAB_ID','99');
 const events=tab(99,[[],['first','First','2026-09-19','2026-09-19',1,'','Open'],['second','Second','2026-09-19','2026-09-19 Other',2,'','Open']]);
 const first=tab(1,[Array.from(headers)]),second=tab(2,[Array.from(headers)]);properties.set('EVENT_first','1');properties.set('EVENT_second','2');
 const payload={event_id:'first',request_id:'a'.repeat(32),origin:'https://bamedicale.com',full_name:'Test Participant',email:' Test.Name+alias@example.invalid ',instagram:true,youtube:true,score:'4',feedback:'',website:''};
 return{c,payload,first,second,events,lock:()=>{locked=true},writes:()=>writes};
}
test('server validates required values, true confirmations, bounds and allowed fields',()=>{const{c,payload:p}=fixture();assert(c.validate_(p));for(const patch of [{full_name:' '},{email:'invalid'},{instagram:'true'},{youtube:false},{score:'6'},{score:''},{feedback:'x'.repeat(301)},{website:'bot'},{tab:'arbitrary'},{event_id:'../../arbitrary'}])assert.equal(c.validate_({...p,...patch}),false);});
test('duplicate acknowledgement preserves manual certificate fields and aliases',()=>{const{c,payload:p,first}=fixture();assert.equal(c.record_(p),'recorded');first.rows[1][8]='Sent';first.rows[1][11]='Keep';assert.equal(c.record_({...p,email:p.email.trim().toLowerCase()}),'duplicate');assert.equal(first.rows.length,2);assert.equal(first.rows[1][8],'Sent');assert.equal(first.rows[1][11],'Keep');assert.equal(c.record_({...p,email:'TestName+alias@example.invalid'}),'recorded');assert.equal(c.record_({...p,email:'Test.Name+other@example.invalid'}),'recorded');});
test('same email and same-date events stay in separately mapped numeric tabs',()=>{const{c,payload:p,first,second,events}=fixture();assert.equal(c.record_(p),'recorded');assert.equal(c.record_({...p,event_id:'second'}),'recorded');assert.equal(first.rows.length,2);assert.equal(second.rows.length,2);events.rows[1][3]='Renamed tab';assert.equal(c.record_(p),'duplicate');events.rows[1][4]=2;assert.equal(c.record_(p),'closed');});
test('closed events and lock contention never write',()=>{const f=fixture();f.events.rows[1][6]='Closed';assert.equal(f.c.record_(f.payload),'closed');f.lock();assert.equal(f.c.record_({...f.payload,event_id:'second'}),'retry');assert.equal(f.writes(),0);});
test('formula strings are escaped and retries preserve the existing row',()=>{const{c,payload:p,first}=fixture();assert.equal(c.record_({...p,full_name:'=IMPORTXML("x")',feedback:' +123'}),'recorded');assert.equal(c.safeCell_('=1'),"'=1");assert.equal(first.rows[1][3],'=IMPORTXML("x")');assert.equal(c.record_(p),'duplicate');});
test('bridge replies contain correlation/status only and reject wrong origins',()=>{const{c,payload:p}=fixture();const result=c.reply_(p,'recorded').text;assert(result.includes(p.request_id));assert(!result.includes(p.email));assert(!result.includes(p.full_name));assert.equal(c.reply_({...p,origin:'https://evil.invalid'},'recorded').text,'Request unavailable.');assert.equal(c.doPost({postData:{length:17000},parameters:{}}).text,'Request unavailable.');});
