const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const QR=require('qrcode'),{PNG}=require('pngjs'),decode=require('jsqr');
const root=path.resolve(__dirname,'../..'),config=require('../../attendance/config.json');
const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'content.js'),'utf8'),context);
const registry=context.window.BAMEDICALE_DATA.seminars;
const check=process.argv.includes('--check');
const ids=[...config.events]; const add=process.argv.find(a=>a.startsWith('--event='))?.slice(8);
assert(!check||!add,'Do not provision during a read-only check');
if(add&&!ids.includes(add)){assert(registry[add],'Unknown registered seminar');ids.push(add);config.events=ids;fs.writeFileSync(path.join(root,'attendance/config.json'),JSON.stringify(config,null,2)+'\n');}
assert.equal(new Set(ids).size,ids.length);assert(!config.endpoint||/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(config.endpoint),'Invalid deployment URL');
function output(file,body){const p=path.join(root,file),buf=Buffer.isBuffer(body)?body:Buffer.from(body);if(check)assert(fs.existsSync(p)&&fs.readFileSync(p).equals(buf),'Stale output: '+file);else {fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,buf)}}
(async()=>{const seeds=[];for(const id of ids){const event=registry[id];assert(event&&event.id===id,'Unknown Event ID');const url=`https://bamedicale.com/attendance/${id}.html`;const opts={errorCorrectionLevel:'M',margin:4,color:{dark:'#000000',light:'#ffffff'}};const svg=await QR.toString(url,{...opts,type:'svg'});const png=await QR.toBuffer(url,{...opts,scale:24,type:'png'});const image=PNG.sync.read(png),decoded=decode(image.data,image.width,image.height);assert.equal(decoded?.data,url,'QR decoding failed');assert(image.width>=1000);output(`assets/attendance/${id}.svg`,svg);output(`assets/attendance/${id}.png`,png);output(`attendance/${id}.html`,require('./template')(event,config.endpoint));seeds.push({id,title:event.title,date:event.startDate.slice(0,10)});}
output('scripts/attendance/Code.gs','// Generated by npm run attendance:build; paste into the existing bound project.\nconst ATTENDANCE_SEEDS = '+JSON.stringify(seeds)+';\n'+fs.readFileSync(path.join(__dirname,'backend.js'),'utf8'));
console.log(`Attendance ${check?'check':'build'} passed: ${ids.length} registered event(s), SVG + high-resolution PNG decoded.`)})().catch(e=>{console.error(e.message);process.exit(1)});
