// Generated by npm run attendance:build; paste into the existing bound project.
const ATTENDANCE_SEEDS = [{"id":"management-thyroid-nodules-2026","title":"Management of Thyroid Nodules — How to Make a Good Diagnosis?","date":"2026-09-19"}];
/* Bound to the existing private tracker. No participant data is logged or returned. */
const ATTENDANCE_HEADERS = ['Date Submitted','Time Submitted','Email','Full Name','Follow IG Y/N','Follow YT Y/N','Your Score for the Seminar','Your Feedback for Seminar','Certificate Status','Certificate Sent Date','Sent By','Notes'];
const EVENT_HEADERS = ['Event ID','Event title','Seminar date','Attendance tab name','Attendance tab ID','Attendance page URL','Manual Override','Open At','Close At'];
const SITE_ORIGIN = 'https://bamedicale.com';
const props_ = () => PropertiesService.getScriptProperties();
const safeCell_ = value => /^[\s]*[=+\-@]/.test(String(value)) ? "'" + value : String(value);
const normalizedEmail_ = value => String(value).trim().toLowerCase();
function assert_(ok, message) { if (!ok) throw new Error(message); }
function header_(sheet, headers) {
  if (!sheet.getLastRow()) sheet.getRange(1,1,1,headers.length).setValues([headers]);
  assert_(JSON.stringify(sheet.getRange(1,1,1,headers.length).getValues()[0]) === JSON.stringify(headers), 'Existing headers differ; review without overwriting data.');
}
function protect_(sheet, a1, label) {
  const previous = sheet.getProtections(SpreadsheetApp.ProtectionType.RANGE).find(p => p.getDescription() === label);
  const protection = previous || sheet.getRange(a1).protect().setDescription(label);
  protection.setRange(sheet.getRange(a1));
  protection.addEditor(Session.getEffectiveUser());
  protection.removeEditors(protection.getEditors().filter(u => u.getEmail() !== Session.getEffectiveUser().getEmail()));
  if (protection.canDomainEdit()) protection.setDomainEdit(false);
}
function formatTab_(sheet) {
  header_(sheet, ATTENDANCE_HEADERS);
  sheet.setFrozenRows(1);
  sheet.getRange(1,1,1,12).setFontWeight('bold').setBackground('#981d36').setFontColor('#ffffff').setWrap(true);
  sheet.setRowHeight(1,52); sheet.setColumnWidths(1,12,160); sheet.setColumnWidth(3,250); sheet.setColumnWidth(4,220); sheet.setColumnWidth(8,350); sheet.setColumnWidth(12,300);
  const filter = sheet.getFilter(); if (!filter) sheet.getRange(1,1,sheet.getMaxRows(),12).createFilter();
  sheet.getRange(2,9,sheet.getMaxRows()-1,1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Pending','Sent','Failed'],true).setAllowInvalid(false).build());
  sheet.getRange(2,10,sheet.getMaxRows()-1,1).setNumberFormat('yyyy-mm-dd hh:mm');
  protect_(sheet,'A:H','Attendance source fields'); protect_(sheet,'I1:L1','Attendance operations headers');
}
/* Only run from the owner's editor. Seed records are generated from content.js. */
function setupAttendance() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  assert_(ss && ss.getName() === 'Seminar Tracker - BA Medicale 2026','Open this script from the existing Seminar Tracker - BA Medicale 2026 spreadsheet.');
  const file = DriveApp.getFileById(ss.getId());
  const owner = file.getOwner().getEmail();
  assert_(owner === Session.getEffectiveUser().getEmail(),'Run setup as the tracker owner.');
  assert_(file.getSharingAccess() === DriveApp.Access.PRIVATE,'Tracker sharing must be Restricted.');
  const oldId = props_().getProperty('TRACKER_ID');
  assert_(!oldId || oldId === ss.getId(),'This backend is already bound to another tracker.');
  const lock = LockService.getScriptLock(); lock.waitLock(5000);
  try {
    ss.setSpreadsheetTimeZone('Asia/Jakarta');
    props_().setProperty('TRACKER_ID',ss.getId());
    props_().setProperty('OWNER',owner);
    const mappedEvents = props_().getProperty('EVENTS_TAB_ID');
    let events = mappedEvents !== null ? ss.getSheetById(Number(mappedEvents)) : ss.getSheetByName('Events');
    assert_(!mappedEvents || events,'Events tab was removed; restore it before continuing.');
    events = events || ss.insertSheet('Events');
    // Migrate the original status column once, preserving mappings and existing closure.
    if(events.getLastRow() && events.getRange(1,7).getValue()==='Attendance status') {
      assert_(JSON.stringify(events.getRange(1,1,1,6).getValues()[0])===JSON.stringify(EVENT_HEADERS.slice(0,6)),'Review existing Events headers.');
      assert_(!events.getRange(1,8).getValue() && !events.getRange(1,9).getValue(),'Schedule columns already occupied; review before migration.');
      events.getRange(2,7,events.getMaxRows()-1,1).clearDataValidations();
      if(events.getLastRow()>1) {
        const values=events.getRange(2,7,events.getLastRow()-1,1).getValues().map(r=>[r[0]==='Open'?'OPEN':'CLOSED']);
        events.getRange(2,7,values.length,1).setValues(values);
      }
      events.getRange(1,1,1,9).setValues([EVENT_HEADERS]);
    }
    header_(events,EVENT_HEADERS);
    props_().setProperty('EVENTS_TAB_ID',String(events.getSheetId()));
    events.setFrozenRows(1); events.setColumnWidths(1,9,190); events.setColumnWidth(2,440); events.setColumnWidth(6,460);
    events.getRange(1,1,1,9).setFontWeight('bold').setBackground('#981d36').setFontColor('#ffffff').setWrap(true);
    events.getRange(2,7,events.getMaxRows()-1,1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['AUTO','OPEN','CLOSED'],true).setAllowInvalid(false).build());
    events.getRange(2,8,events.getMaxRows()-1,2).setNumberFormat('dd mmm yyyy hh:mm');
    const eventFilter=events.getFilter(); if(eventFilter && eventFilter.getRange().getNumColumns()!==9) eventFilter.remove();
    if (!events.getFilter()) events.getRange(1,1,events.getMaxRows(),9).createFilter();
    protect_(events,'A:F','Approved seminar mapping'); protect_(events,'G1:I1','Attendance status header');
    const existing = events.getLastRow()>1 ? events.getRange(2,1,events.getLastRow()-1,9).getValues() : [];
    ATTENDANCE_SEEDS.forEach(event => {
      const matches = existing.filter(r => r[0] === event.id); assert_(matches.length <= 1,'Duplicate Event ID in Events.');
      const stored = props_().getProperty('EVENT_'+event.id);
      let tab;
      if (matches.length) {
        assert_(stored !== null && Number(stored) === Number(matches[0][4]),'Existing event mapping requires owner review.');
        tab = ss.getSheetById(Number(stored)); assert_(tab,'Mapped attendance tab was removed; do not replace it.');
      } else {
        assert_(stored === null,'Event mapping was removed from Events; restore it before setup.');
        let title = event.date.slice(8,10)+' '+['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][Number(event.date.slice(5,7))-1]+' '+event.date.slice(0,4);
        // Reuse the user's original empty date tab, never silently overwrite a populated tab.
        const legacy = ss.getSheetByName(event.date.replace(/-/g,'').replace(/^(\d{4})(\d{2})(\d{2})$/,'$3$2$1'));
        const candidate = ss.getSheetByName(title);
        const claimed = existing.some(r => Number(r[4]) === (candidate && candidate.getSheetId()));
        if (candidate && claimed) title += ' - '+event.id.slice(0,35);
        tab = ss.getSheetByName(title);
        assert_(!tab || !existing.some(r => Number(r[4]) === tab.getSheetId()),'Attendance tab belongs to another event.');
        if (!tab && legacy && !legacy.getLastRow()) { tab = legacy; tab.setName(title); }
        tab = tab || ss.insertSheet(title); header_(tab,ATTENDANCE_HEADERS);
        props_().setProperty('EVENT_'+event.id,String(tab.getSheetId()));
        const row = [event.id,event.title,event.date,tab.getName(),tab.getSheetId(),SITE_ORIGIN+'/attendance/'+event.id+'.html','AUTO','',''];
        events.appendRow(row); existing.push(row);
      }
      formatTab_(tab);
    });
    SpreadsheetApp.flush();
  } finally { lock.releaseLock(); }
}
function event_(id) {
  if (typeof id !== 'string' || !/^[a-z0-9-]{1,100}$/.test(id)) return null;
  const p=props_(), mapped=p.getProperty('EVENT_'+id); if(mapped===null) return null;
  const ss=SpreadsheetApp.openById(p.getProperty('TRACKER_ID'));
  const events=ss.getSheetById(Number(p.getProperty('EVENTS_TAB_ID')));
  if(!events || events.getLastRow()<2) return null;
  const rows=events.getRange(2,1,events.getLastRow()-1,9).getValues().filter(r=>r[0]===id);
  if(rows.length!==1 || Number(rows[0][4])!==Number(mapped)) return null;
  const tab=ss.getSheetById(Number(mapped)); if(!tab) return null;
  const resolved=resolveSchedule_(rows[0][6],rows[0][7],rows[0][8],Date.now());
  return {tab,...resolved};
}
// Sheet datetime cells are instants; explicit text is interpreted in WIB, never browser/server local time.
function scheduleTime_(value) {
  if(Object.prototype.toString.call(value)==='[object Date]') return value.getTime();
  if(typeof value!=='string') return NaN;
  const m=value.trim().match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})$/);
  if(!m) return NaN;
  const iso=m[1]+'-'+m[2]+'-'+m[3]+'T'+m[4]+':'+m[5]+':00+07:00';
  const time=Date.parse(iso);
  return Number.isFinite(time) && new Date(time+7*3600000).toISOString().slice(0,16)===iso.slice(0,16) ? time : NaN;
}
function resolveSchedule_(override,openAt,closeAt,now) {
  if(override==='OPEN') return {open:true,state:'FORCED_OPEN'};
  if(override==='CLOSED') return {open:false,state:'FORCED_CLOSED'};
  const start=scheduleTime_(openAt),end=scheduleTime_(closeAt);
  if(override!=='AUTO' || !Number.isFinite(start) || !Number.isFinite(end) || end<=start || !Number.isFinite(now)) return {open:false,state:'CLOSED_INVALID'};
  if(now<start) return {open:false,state:'CLOSED_BEFORE',opensAt:Utilities.formatDate(new Date(start),'Asia/Jakarta','dd MMM yyyy \'at\' HH:mm')+' WIB'};
  return now<end ? {open:true,state:'OPEN'} : {open:false,state:'CLOSED_AFTER'};
}
function validate_(p) {
  const keys=['event_id','request_id','origin','full_name','email','instagram','youtube','score','feedback','website'];
  if(!p || typeof p!=='object' || Array.isArray(p) || Object.keys(p).some(k=>!keys.includes(k))) return false;
  if(typeof p.event_id!=='string' || !/^[a-z0-9-]{1,100}$/.test(p.event_id)) return false;
  if(typeof p.full_name!=='string' || !p.full_name.trim() || p.full_name.length>120 || /[\x00-\x1f\x7f]/.test(p.full_name)) return false;
  if(typeof p.email!=='string' || p.email.length>254 || /[\x00-\x1f\x7f]/.test(p.email)) return false;
  const email=p.email.trim();
  if(!/^[^\s@<>]+@[^\s@<>.]+(?:\.[^\s@<>.]+)+$/.test(email) || email.split('@')[0].length>64) return false;
  if(p.instagram!==true || p.youtube!==true || p.website!=='') return false;
  return typeof p.score==='string' && /^[1-5]$/.test(p.score) && typeof p.feedback==='string' && p.feedback.length<=300 && !/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(p.score+p.feedback);
}
function record_(p) {
  if(!validate_(p)) return 'invalid';
  const lock=LockService.getScriptLock(); if(!lock.tryLock(3000)) return 'retry';
  try {
    const event=event_(p.event_id); if(!event || !event.open) return event ? event.state : 'CLOSED_INVALID';
    header_(event.tab,ATTENDANCE_HEADERS);
    const n=event.tab.getLastRow(); if(n>10000) return 'retry';
    const emails=n>1 ? event.tab.getRange(2,3,n-1,1).getValues() : [];
    if(emails.some(r=>normalizedEmail_(r[0])===normalizedEmail_(p.email))) return 'duplicate';
    const minute=String(Math.floor(Date.now()/60000)), rate=JSON.parse(props_().getProperty('RATE')||'{}');
    const count=rate.minute===minute ? rate.count : 0; if(count>=120) return 'retry';
    props_().setProperty('RATE',JSON.stringify({minute,count:count+1}));
    const now=new Date();
    const row=[Utilities.formatDate(now,'Asia/Jakarta','yyyy-MM-dd'),Utilities.formatDate(now,'Asia/Jakarta','HH:mm:ss'),safeCell_(p.email),safeCell_(p.full_name),'Y','Y',safeCell_(p.score),safeCell_(p.feedback),'Pending','','',''];
    if(n===event.tab.getMaxRows()) { event.tab.insertRowsAfter(n,100); formatTab_(event.tab); }
    const target=event.tab.getRange(n+1,1,1,12); target.setNumberFormat('@'); target.setValues([row]);
    event.tab.getRange(n+1,10).setNumberFormat('yyyy-mm-dd hh:mm');
    SpreadsheetApp.flush();
    // Acknowledgement follows a readback of persistence, never just dispatch.
    const saved=target.getValues()[0];
    if(normalizedEmail_(saved[2])!==normalizedEmail_(p.email) || saved[8]!=='Pending') return 'retry';
    return 'recorded';
  } finally { lock.releaseLock(); }
}
function correlation_(p) {
  return p && p.origin===SITE_ORIGIN && typeof p.event_id==='string' && /^[a-z0-9-]{1,100}$/.test(p.event_id) && /^[a-f0-9]{32}$/.test(p.request_id||'');
}
function ackKey_(p) { return 'ACK_'+p.event_id+'_'+p.request_id; }
function reply_(p,status,opensAt) {
  if(!correlation_(p) || p.callback!=='baAttendance_'+p.request_id) return ContentService.createTextOutput('Request unavailable.');
  // Read-only JSONP returns only non-sensitive request status, never participant data.
  const message=JSON.stringify({type:'ba-attendance',request_id:p.request_id,event_id:p.event_id,status,...(status==='CLOSED_BEFORE' && opensAt?{opens_at:opensAt}:{})});
  return ContentService.createTextOutput('typeof '+p.callback+'==="function"&&'+p.callback+'('+message+');').setMimeType(ContentService.MimeType.JAVASCRIPT);
}
function doGet(e) {
  const p=e && e.parameter; let status='CLOSED_INVALID',opensAt;
  if(p && /^quiz_/.test(p.action||''))return quizGet_(p);
  if(p && p.action==='download_ack')return downloadReply_(p);
  if(!correlation_(p)) return reply_(null,status);
  try {
    if(p.action==='ack') status=CacheService.getScriptCache().get(ackKey_(p))||'waiting';
    else if(p.action==='status') { const target=event_(p.event_id); if(target) {status=target.state;opensAt=target.opensAt;} }
    else status='invalid';
    if(status==='CLOSED_BEFORE' && !opensAt) opensAt=event_(p.event_id)?.opensAt;
  } catch(_) { status='retry'; }
  return reply_(p,status,opensAt);
}
function doPost(e) {
  let p; let status='invalid';
  try {
    if(!e || !e.postData || e.postData.length>16000 || Object.keys(e.parameters).some(k=>k!=='payload') || !e.parameters.payload || e.parameters.payload.length!==1) return ContentService.createTextOutput('Request unavailable.');
    p=JSON.parse(e.parameter.payload);
    if(p && /^quiz_/.test(p.action||'')){if(e.postData.length>4096)return ContentService.createTextOutput('Request unavailable.');return quizPost_(p);}
    if(p && p.action==='download'){
      if(e.postData.length>2048)return ContentService.createTextOutput('Request unavailable.');
      try{status=recordDownload_(p);}catch(_){status='retry';}
      if(downloadCorrelation_(p))CacheService.getScriptCache().put(downloadAckKey_(p),status,180);
      return ContentService.createTextOutput('Request processed.');
    }
    if(correlation_(p)) status=record_(p);
  } catch(_) {status='retry';}
  if(correlation_(p)) CacheService.getScriptCache().put(ackKey_(p),status,180);
  // This POST response is not treated as success. The browser reads its correlated acknowledgement.
  return ContentService.createTextOutput('Request processed. Return to the attendance page.');
}

/* Download activity only. Six visible columns; durable per-attempt markers use cell notes. */
const DOWNLOAD_HEADERS = ['Date Submitted','Time Submitted','Email','Material','Event','Download Status'];
const DOWNLOAD_MATERIAL_ID = 'current-diagnostic-approach-and-therapy-selection-for-thyroid-nodules';
const DOWNLOAD_MATERIAL = 'Current Diagnostic Approach and Therapy Selection for Thyroid Nodules';
const DOWNLOAD_EVENT = '19 Sep 2026 — Management of Thyroid Nodules';
const DOWNLOAD_MATERIALS = {
  [DOWNLOAD_MATERIAL_ID]: DOWNLOAD_MATERIAL,
  'ultrasound-imaging-and-tirads-classification-in-thyroid-nodules': 'Ultrasound Imaging and TIRADS Classification in Thyroid Nodules',
  'bethesda-system-for-reporting-thyroid-cytopathology': 'Bethesda System for Reporting Thyroid Cytopathology'
};
function setupDownloads() {
  const ss=SpreadsheetApp.getActiveSpreadsheet();
  assert_(ss && ss.getId()===props_().getProperty('TRACKER_ID'),'Use the existing bound tracker.');
  assert_(DriveApp.getFileById(ss.getId()).getOwner().getEmail()===Session.getEffectiveUser().getEmail(),'Run as tracker owner.');
  const lock=LockService.getScriptLock();lock.waitLock(5000);
  try {
    let sheet=ss.getSheetByName('Download Material');
    sheet=sheet||ss.insertSheet('Download Material');header_(sheet,DOWNLOAD_HEADERS);
    assert_(sheet.getLastColumn()<=6,'Unexpected download columns; review without overwriting.');
    sheet.setFrozenRows(1);sheet.setColumnWidths(1,6,160);sheet.setColumnWidth(3,260);sheet.setColumnWidth(4,520);sheet.setColumnWidth(5,420);
    sheet.getRange(1,1,1,6).setFontWeight('bold').setBackground('#981d36').setFontColor('#ffffff').setWrap(true);
    if(!sheet.getFilter())sheet.getRange(1,1,sheet.getMaxRows(),6).createFilter();
    props_().setProperty('DOWNLOAD_TAB_ID',String(sheet.getSheetId()));SpreadsheetApp.flush();
  } finally {lock.releaseLock();}
}
function downloadCorrelation_(p) {
  return p && p.origin===SITE_ORIGIN && Object.prototype.hasOwnProperty.call(DOWNLOAD_MATERIALS,p.material_id) && typeof p.request_id==='string' && /^[a-f0-9]{32}$/.test(p.request_id);
}
function validateDownload_(p) {
  if(!downloadCorrelation_(p)||p.action!=='download'||Object.keys(p).some(k=>!['action','material_id','request_id','origin','email'].includes(k)))return false;
  if(typeof p.email!=='string'||p.email.length>254||/[\x00-\x1f\x7f]/.test(p.email))return false;
  const email=p.email.trim();
  return /^[^\s@<>]+@[^\s@<>.]+(?:\.[^\s@<>.]+)+$/.test(email)&&email.split('@')[0].length<=64;
}
function downloadAckKey_(p){return 'DOWNLOAD_ACK_'+p.request_id;}
function recordDownload_(p) {
  if(!validateDownload_(p))return 'invalid';
  const materialTitle=DOWNLOAD_MATERIALS[p.material_id];
  const lock=LockService.getScriptLock();if(!lock.tryLock(5000))return 'retry';
  try {
    const id=props_().getProperty('DOWNLOAD_TAB_ID');if(id===null)return 'retry';
    const sheet=SpreadsheetApp.openById(props_().getProperty('TRACKER_ID')).getSheetById(Number(id));
    if(!sheet||sheet.getName()!=='Download Material')return 'retry';header_(sheet,DOWNLOAD_HEADERS);
    if(sheet.getMaxRows()>20000)return 'retry';
    const notes=sheet.getRange(2,1,sheet.getMaxRows()-1,1).getNotes();
    const prefix='ba-download:'+p.request_id+':';
    const digest=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,normalizedEmail_(p.email)).map(b=>('0'+(b&255).toString(16)).slice(-2)).join('');
    const marker=prefix+digest+(p.material_id===DOWNLOAD_MATERIAL_ID?'':':'+p.material_id);
    let row=notes.findIndex(r=>r[0].startsWith(prefix));
    if(row>=0){if(notes[row][0]!==marker)return 'invalid';row+=2;}
    else {
      const minute=String(Math.floor(Date.now()/60000)),rate=JSON.parse(props_().getProperty('DOWNLOAD_RATE')||'{}');
      const count=rate.minute===minute?rate.count:0;if(count>=120)return 'retry';
      props_().setProperty('DOWNLOAD_RATE',JSON.stringify({minute,count:count+1}));
      const lastReserved=notes.reduce((last,r,i)=>r[0]?i+2:last,1);
      row=Math.max(sheet.getLastRow(),lastReserved)+1;
      if(row>20000)return 'retry';
      if(row>sheet.getMaxRows())sheet.insertRowsAfter(sheet.getMaxRows(),100);
      // Reserve first. A retry can recover a partially written row without duplicating it.
      sheet.getRange(row,1).setNote(marker);SpreadsheetApp.flush();
    }
    const target=sheet.getRange(row,1,1,6),saved=target.getValues()[0];
    if(saved[5]==='Downloaded'&&saved[3]===materialTitle&&saved[4]===DOWNLOAD_EVENT&&normalizedEmail_(saved[2])===normalizedEmail_(p.email))return 'recorded';
    if(saved.some(v=>v!==''))return 'retry';
    const now=new Date(),values=[Utilities.formatDate(now,'Asia/Jakarta','yyyy-MM-dd'),Utilities.formatDate(now,'Asia/Jakarta','HH:mm:ss'),safeCell_(p.email.trim()),materialTitle,DOWNLOAD_EVENT,'Downloaded'];
    target.setNumberFormat('@').setValues([values]);SpreadsheetApp.flush();
    const check=target.getValues()[0];
    return check[0]===values[0]&&check[1]===values[1]&&normalizedEmail_(check[2])===normalizedEmail_(p.email)&&check[3]===materialTitle&&check[4]===DOWNLOAD_EVENT&&check[5]==='Downloaded'?'recorded':'retry';
  } finally {lock.releaseLock();}
}
function downloadReply_(p) {
  if(!downloadCorrelation_(p)||p.callback!=='baDownload_'+p.request_id||Object.keys(p).some(k=>!['action','material_id','request_id','origin','callback','attempt'].includes(k)))return ContentService.createTextOutput('Request unavailable.');
  let status='retry';try{status=CacheService.getScriptCache().get(downloadAckKey_(p))||'waiting';}catch(_){}
  return ContentService.createTextOutput('typeof '+p.callback+'==="function"&&'+p.callback+'('+JSON.stringify({type:'ba-download',request_id:p.request_id,status})+');').setMimeType(ContentService.MimeType.JAVASCRIPT);
}

/* Apps Script server module. Real answer keys live ONLY in private Script Properties. */
const QUIZ_HEADERS = ['Date Submitted','Time Submitted','Email','Correct Answers','Total Questions','Result %','Time Taken Seconds','Quiz Status','Session ID','Submitted At'];
const QUIZ_SESSION_HEADERS = ['Event ID','Email','Start Request','Session ID','Started At'];
const QUIZ_CONTROL_HEADERS = ['Event ID','Manual Override','Result Tab ID','Open At','Close At'];
const QUIZ_DURATION = 180000, QUIZ_GRACE = 5000;
function quizConfig_(id) {
  try {
  if(!/^[a-z0-9-]{1,100}$/.test(id||''))return null;
  const raw=props_().getProperty('QUIZ_KEY_'+id); if(!raw)return null;
  const key=JSON.parse(raw); if(!Array.isArray(key)||key.length!==5||key.some(x=>!Number.isInteger(x)||x<0||x>3))return null;
  const ss=SpreadsheetApp.openById(props_().getProperty('TRACKER_ID'));
  const control=ss.getSheetByName('Quiz Control'); if(!control||control.getLastRow()<2)return null;
  const row=control.getRange(2,1,control.getLastRow()-1,5).getValues().find(r=>r[0]===id);
  if(!row)return null;
  const sheet=ss.getSheetById(Number(row[2])),sessions=ss.getSheetByName('Quiz Sessions');
  if(!sheet||!sessions)return null;
  return {id,key,sheet,sessions,compact:id==='lms-management-thyroid-nodules-2026',title:id==='lms-management-thyroid-nodules-2026'?'LMS Live Quiz':'BA Medicale Live Quiz',...resolveSchedule_(row[1],row[3],row[4],Date.now())};
  }catch(_){return null;}
}
/* Owner-only provisioning. Set QUIZ_KEY_<event-id> privately before running. */
function setupQuiz() { setupQuizDefinition_('management-thyroid-nodules-2026','BAGames19Sep',QUIZ_HEADERS); }
function setupLmsQuiz() { setupQuizDefinition_('lms-management-thyroid-nodules-2026','LMSGames19Sep',QUIZ_HEADERS.slice(0,8)); }
function setupQuizDefinition_(id,tabName,headers) {
  const ss=SpreadsheetApp.getActiveSpreadsheet();
  assert_(ss&&ss.getId()===props_().getProperty('TRACKER_ID'),'Use the existing bound tracker.');
  assert_(Session.getEffectiveUser().getEmail()===props_().getProperty('OWNER'),'Owner only.');
  assert_(DriveApp.getFileById(ss.getId()).getSharingAccess()===DriveApp.Access.PRIVATE,'Keep tracker Restricted.');
  const lock=LockService.getScriptLock();lock.waitLock(10000);
  try {
    const key=JSON.parse(props_().getProperty('QUIZ_KEY_'+id)||'null');
    assert_(Array.isArray(key)&&key.length===5&&key.every(n=>Number.isInteger(n)&&n>=0&&n<4),'Set the verified private answer key first.');
    const control=ss.getSheetByName('Quiz Control')||ss.insertSheet('Quiz Control');if(control.getLastRow()&&JSON.stringify(control.getRange(1,1,1,3).getValues()[0])===JSON.stringify(['Event ID','State','Result Tab ID'])){
      assert_(!control.getRange(1,4).getValue()&&!control.getRange(1,5).getValue(),'Schedule columns occupied; review first.');
      control.getRange(1,1,1,5).setValues([QUIZ_CONTROL_HEADERS]);
    }
    header_(control,QUIZ_CONTROL_HEADERS);
    const sessions=ss.getSheetByName('Quiz Sessions')||ss.insertSheet('Quiz Sessions');header_(sessions,QUIZ_SESSION_HEADERS);
    const sheet=ss.getSheetByName(tabName)||ss.insertSheet(tabName);header_(sheet,headers);
    const rows=control.getLastRow()>1?control.getRange(2,1,control.getLastRow()-1,3).getValues():[];
    const existing=rows.find(r=>r[0]===id);
    assert_(!existing||Number(existing[2])===sheet.getSheetId(),'Preserve existing quiz mapping.');
    if(!existing)control.appendRow([id,'AUTO',sheet.getSheetId(),'','']);
    [control,sessions,sheet].forEach(tab=>{tab.setFrozenRows(1);tab.setColumnWidths(1,tab.getLastColumn(),170);tab.getRange(1,1,1,tab.getLastColumn()).setFontWeight('bold').setBackground('#981d36').setFontColor('#ffffff');if(!tab.getFilter())tab.getRange(1,1,tab.getMaxRows(),tab.getLastColumn()).createFilter();});
    control.setColumnWidth(1,330);sheet.setColumnWidth(3,280);sessions.setColumnWidth(2,280);
    control.getRange(2,2,control.getMaxRows()-1,1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['AUTO','OPEN','CLOSED'],true).setAllowInvalid(false).build());
    control.getRange(2,4,control.getMaxRows()-1,2).setNumberFormat('dd mmm yyyy hh:mm');
    const filter=control.getFilter();if(filter&&filter.getRange().getNumColumns()!==5)filter.remove();if(!control.getFilter())control.getRange(1,1,control.getMaxRows(),5).createFilter();
    SpreadsheetApp.flush();
  }finally{lock.releaseLock();}
}
function quizRows_(sheet,cols){return sheet.getLastRow()>1?sheet.getRange(2,1,sheet.getLastRow()-1,cols).getValues():[];}
function quizEmail_(value){return String(value).replace(/^'/,'').trim().toLowerCase();}
function quizMask_(email){const [local,domain]=quizEmail_(email).split('@');return local.slice(0,Math.min(2,Math.max(1,local.length-1)))+'***@'+domain;}
function quizResult_(row){return {status:'completed',correct:Number(row[3]),total:5,percentage:Number(row[5]),elapsed:Number(row[6])};}
function quizScore_(answers,key,elapsed){return elapsed>QUIZ_DURATION+QUIZ_GRACE?0:answers.reduce((n,a,i)=>n+(a===key[i]?1:0),0);}
function quizLeaderboard_(rows){return rows.filter(r=>r[7]==='Completed').sort((a,b)=>Number(b[5])-Number(a[5])||Number(a[6])-Number(b[6])||Number(a[9])-Number(b[9])).slice(0,5).map((r,i)=>({rank:i+1,email:quizMask_(r[2]),percentage:Number(r[5]),elapsed:Number(r[6])}));}
function quizValidate_(p){
  if(!p||typeof p!=='object'||Array.isArray(p)||p.origin!==SITE_ORIGIN||!/^quiz_(start|resume|submit)$/.test(p.action||'')||!/^[a-f0-9]{32}$/.test(p.request_id||'')||!/^[a-z0-9-]{1,100}$/.test(p.event_id||''))return false;
  const allowed=['action','origin','event_id','request_id',...(p.action==='quiz_start'?['email','start_id']:['token']),...(p.action==='quiz_submit'?['answers']:[])];
  if(Object.keys(p).some(k=>!allowed.includes(k)))return false;
  if(p.action==='quiz_start')return typeof p.email==='string'&&p.email.length<=254&&p.email.trim().split('@')[0].length<=64&&/^[^\s@<>\x00-\x1f]+@[^\s@<>.]+(?:\.[^\s@<>.]+)+$/.test(p.email.trim())&&/^[a-f0-9]{32}$/.test(p.start_id||'');
  if(!/^[a-f0-9]{64}$/.test(p.token||''))return false;
  return p.action!=='quiz_submit'||Array.isArray(p.answers)&&p.answers.length===5&&p.answers.every(n=>n===null||Number.isInteger(n)&&n>=0&&n<4);
}
function quizRecord_(p){
  if(!quizValidate_(p))return {status:'invalid'};
  const lock=LockService.getScriptLock();if(!lock.tryLock(10000))return {status:'retry'};
  try{
    const q=quizConfig_(p.event_id);if(!q)return {status:'closed'};
    const results=quizResults_(q),sessions=quizRows_(q.sessions,5);
    let session;
    if(p.action==='quiz_start'){
      const email=normalizedEmail_(p.email);
      if(results.some(r=>quizEmail_(r[2])===email))return {status:'already_completed'};
      session=sessions.find(r=>r[0]===q.id&&quizEmail_(r[1])===email);
      if(session&&session[2]!==p.start_id)return {status:'already_started'};
      if(!q.open)return quizAvailability_(q);
      if(!session){
        if(sessions.length>=20000)return {status:'retry'};
        session=[q.id,safeCell_(email),p.start_id,(Utilities.getUuid()+Utilities.getUuid()).replace(/-/g,''),Date.now()];
        q.sessions.appendRow(session);SpreadsheetApp.flush();
      }
    }else session=sessions.find(r=>r[0]===q.id&&r[3]===p.token);
    if(!session)return {status:'invalid'};
    const existing=results.find(r=>q.compact?quizEmail_(r[2])===quizEmail_(session[1]):r[8]===session[3]);if(existing)return quizResult_(existing);
    const now=Date.now(),elapsed=now-Number(session[4]);
    if(p.action!=='quiz_submit'&&elapsed<=QUIZ_DURATION+QUIZ_GRACE)return {status:'active',token:session[3],startedAt:Number(session[4]),deadline:Number(session[4])+QUIZ_DURATION,serverNow:now};
    // Expired sessions cannot gain extra answering time; late retries return the stored result.
    const correct=quizScore_(p.action==='quiz_submit'?p.answers:[null,null,null,null,null],q.key,elapsed);
    const row=[Utilities.formatDate(new Date(now),'Asia/Jakarta','yyyy-MM-dd'),Utilities.formatDate(new Date(now),'Asia/Jakarta','HH:mm:ss'),session[1],correct,5,correct*20,Math.min(180,Math.max(0,elapsed/1000)), 'Completed',session[3],now];
    q.sheet.appendRow(q.compact?row.slice(0,8):row);SpreadsheetApp.flush();
    return quizResult_(row);
  }finally{lock.releaseLock();}
}
function quizPost_(p){
  const result=quizRecord_(p);
  if(quizValidate_(p))CacheService.getScriptCache().put('QUIZ_ACK_'+p.request_id,JSON.stringify(result),180);
  // Avoid a ContentService POST redirect that Google may reject inside an iframe.
  // The authoritative result still comes from the correlated acknowledgement.
  return HtmlService.createHtmlOutput('Quiz request processed.').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}
function quizGet_(p){
  if(!p||p.origin!==SITE_ORIGIN||!/^[a-f0-9]{32}$/.test(p.request_id||'')||p.callback!=='baQuiz_'+p.request_id||Object.keys(p).some(k=>!['action','origin','event_id','request_id','callback'].includes(k)))return ContentService.createTextOutput('Request unavailable.');
  let result={status:'retry'};
  try{
    if(p.action==='quiz_ack')result=JSON.parse(CacheService.getScriptCache().get('QUIZ_ACK_'+p.request_id)||'{"status":"waiting"}');
    else {const q=quizConfig_(p.event_id);if(p.action==='quiz_status')result=quizAvailability_(q);else if(p.action==='quiz_top')result={status:'ok',players:q?quizLeaderboard_(quizResults_(q)):[]};}
  }catch(_){if(p.action==='quiz_status')result=quizAvailability_(null);}
  if(result.status==='active')result.serverNow=Date.now();
  return ContentService.createTextOutput('typeof '+p.callback+'==="function"&&'+p.callback+'('+JSON.stringify(result)+');').setMimeType(ContentService.MimeType.JAVASCRIPT);
}

function quizAvailability_(q){
  if(q&&q.open)return {status:'open'};
  return {status:'closed',message:q&&q.state==='CLOSED_BEFORE'&&q.opensAt?(q.title||'BA Medicale Live Quiz')+' opens '+q.opensAt+'.':'The '+(q&&q.title||'BA Medicale Live Quiz')+' is closed.'};
}

// The LMS result tab has exactly eight columns; secret tokens stay in Quiz Sessions.
function quizResults_(q){
  const rows=quizRows_(q.sheet,q.compact?8:10);
  if(!q.compact)return rows;
  return rows.map(r=>{const date=r[0] instanceof Date?Utilities.formatDate(r[0],'Asia/Jakarta','yyyy-MM-dd'):String(r[0]);const time=r[1] instanceof Date?Utilities.formatDate(r[1],'Asia/Jakarta','HH:mm:ss'):String(r[1]);return [...r,'',Date.parse(date+'T'+time+'+07:00')];});
}
