// Generated by npm run attendance:build; paste into the existing bound project.
const ATTENDANCE_SEEDS = [{"id":"management-thyroid-nodules-2026","title":"Management of Thyroid Nodules — How to Make an Accurate Diagnosis?","date":"2026-09-19"}];
/* Bound to the existing private tracker. No participant data is logged or returned. */
const ATTENDANCE_HEADERS = ['Date Submitted','Time Submitted','Email','Full Name','Follow IG Y/N','Follow YT Y/N','Your Score for the Seminar','Your Feedback for Seminar','Certificate Status','Certificate Sent Date','Sent By','Notes'];
const EVENT_HEADERS = ['Event ID','Event title','Seminar date','Attendance tab name','Attendance tab ID','Attendance page URL','Attendance status'];
const SITE_ORIGIN = 'https://bamedicale.com';
const props_ = () => PropertiesService.getScriptProperties();
const safeCell_ = value => /^[\s]*[=+\-@]/.test(String(value)) ? "'" + value : String(value);
const normalizedEmail_ = value => String(value).trim().toLowerCase();
function assert_(ok, message) { if (!ok) throw new Error(message); }
function header_(sheet, headers) {
  if (!sheet.getLastRow()) sheet.getRange(1,1,1,headers.length).setValues([headers]);
  assert_(JSON.stringify(sheet.getRange(1,1,1,headers.length).getValues()[0]) === JSON.stringify(headers), 'Existing headers differ; review without overwriting data.');
}
function protect_(sheet, a1, label) {
  const previous = sheet.getProtections(SpreadsheetApp.ProtectionType.RANGE).find(p => p.getDescription() === label);
  const protection = previous || sheet.getRange(a1).protect().setDescription(label);
  protection.setRange(sheet.getRange(a1));
  protection.addEditor(Session.getEffectiveUser());
  protection.removeEditors(protection.getEditors().filter(u => u.getEmail() !== Session.getEffectiveUser().getEmail()));
  if (protection.canDomainEdit()) protection.setDomainEdit(false);
}
function formatTab_(sheet) {
  header_(sheet, ATTENDANCE_HEADERS);
  sheet.setFrozenRows(1);
  sheet.getRange(1,1,1,12).setFontWeight('bold').setBackground('#981d36').setFontColor('#ffffff').setWrap(true);
  sheet.setRowHeight(1,52); sheet.setColumnWidths(1,12,160); sheet.setColumnWidth(3,250); sheet.setColumnWidth(4,220); sheet.setColumnWidth(8,350); sheet.setColumnWidth(12,300);
  const filter = sheet.getFilter(); if (!filter) sheet.getRange(1,1,sheet.getMaxRows(),12).createFilter();
  sheet.getRange(2,9,sheet.getMaxRows()-1,1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Pending','Sent','Failed'],true).setAllowInvalid(false).build());
  sheet.getRange(2,10,sheet.getMaxRows()-1,1).setNumberFormat('yyyy-mm-dd hh:mm');
  protect_(sheet,'A:H','Attendance source fields'); protect_(sheet,'I1:L1','Attendance operations headers');
}
/* Only run from the owner's editor. Seed records are generated from content.js. */
function setupAttendance() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  assert_(ss && ss.getName() === 'Seminar Tracker - BA Medicale 2026','Open this script from the existing Seminar Tracker - BA Medicale 2026 spreadsheet.');
  const file = DriveApp.getFileById(ss.getId());
  const owner = file.getOwner().getEmail();
  assert_(owner === Session.getEffectiveUser().getEmail(),'Run setup as the tracker owner.');
  assert_(file.getSharingAccess() === DriveApp.Access.PRIVATE,'Tracker sharing must be Restricted.');
  const oldId = props_().getProperty('TRACKER_ID');
  assert_(!oldId || oldId === ss.getId(),'This backend is already bound to another tracker.');
  const lock = LockService.getScriptLock(); lock.waitLock(5000);
  try {
    ss.setSpreadsheetTimeZone('Asia/Jakarta');
    props_().setProperty('TRACKER_ID',ss.getId());
    props_().setProperty('OWNER',owner);
    const mappedEvents = props_().getProperty('EVENTS_TAB_ID');
    let events = mappedEvents !== null ? ss.getSheetById(Number(mappedEvents)) : ss.getSheetByName('Events');
    assert_(!mappedEvents || events,'Events tab was removed; restore it before continuing.');
    events = events || ss.insertSheet('Events'); header_(events,EVENT_HEADERS);
    props_().setProperty('EVENTS_TAB_ID',String(events.getSheetId()));
    events.setFrozenRows(1); events.setColumnWidths(1,7,190); events.setColumnWidth(2,440); events.setColumnWidth(6,460);
    events.getRange(1,1,1,7).setFontWeight('bold').setBackground('#981d36').setFontColor('#ffffff').setWrap(true);
    events.getRange(2,7,events.getMaxRows()-1,1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Open','Closed'],true).setAllowInvalid(false).build());
    if (!events.getFilter()) events.getRange(1,1,events.getMaxRows(),7).createFilter();
    protect_(events,'A:F','Approved seminar mapping'); protect_(events,'G1','Attendance status header');
    const existing = events.getLastRow()>1 ? events.getRange(2,1,events.getLastRow()-1,7).getValues() : [];
    ATTENDANCE_SEEDS.forEach(event => {
      const matches = existing.filter(r => r[0] === event.id); assert_(matches.length <= 1,'Duplicate Event ID in Events.');
      const stored = props_().getProperty('EVENT_'+event.id);
      let tab;
      if (matches.length) {
        assert_(stored !== null && Number(stored) === Number(matches[0][4]),'Existing event mapping requires owner review.');
        tab = ss.getSheetById(Number(stored)); assert_(tab,'Mapped attendance tab was removed; do not replace it.');
      } else {
        assert_(stored === null,'Event mapping was removed from Events; restore it before setup.');
        let title = event.date.slice(8,10)+' '+['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][Number(event.date.slice(5,7))-1]+' '+event.date.slice(0,4);
        // Reuse the user's original empty date tab, never silently overwrite a populated tab.
        const legacy = ss.getSheetByName(event.date.replace(/-/g,'').replace(/^(\d{4})(\d{2})(\d{2})$/,'$3$2$1'));
        const candidate = ss.getSheetByName(title);
        const claimed = existing.some(r => Number(r[4]) === (candidate && candidate.getSheetId()));
        if (candidate && claimed) title += ' - '+event.id.slice(0,35);
        tab = ss.getSheetByName(title);
        assert_(!tab || !existing.some(r => Number(r[4]) === tab.getSheetId()),'Attendance tab belongs to another event.');
        if (!tab && legacy && !legacy.getLastRow()) { tab = legacy; tab.setName(title); }
        tab = tab || ss.insertSheet(title); header_(tab,ATTENDANCE_HEADERS);
        props_().setProperty('EVENT_'+event.id,String(tab.getSheetId()));
        const row = [event.id,event.title,event.date,tab.getName(),tab.getSheetId(),SITE_ORIGIN+'/attendance/'+event.id+'.html','Closed'];
        events.appendRow(row); existing.push(row);
      }
      formatTab_(tab);
    });
    SpreadsheetApp.flush();
  } finally { lock.releaseLock(); }
}
function event_(id) {
  if (typeof id !== 'string' || !/^[a-z0-9-]{1,100}$/.test(id)) return null;
  const p=props_(), mapped=p.getProperty('EVENT_'+id); if(mapped===null) return null;
  const ss=SpreadsheetApp.openById(p.getProperty('TRACKER_ID'));
  const events=ss.getSheetById(Number(p.getProperty('EVENTS_TAB_ID')));
  if(!events || events.getLastRow()<2) return null;
  const rows=events.getRange(2,1,events.getLastRow()-1,7).getValues().filter(r=>r[0]===id);
  if(rows.length!==1 || Number(rows[0][4])!==Number(mapped)) return null;
  const tab=ss.getSheetById(Number(mapped)); if(!tab) return null;
  return {tab,open:rows[0][6]==='Open'};
}
function validate_(p) {
  const keys=['event_id','request_id','origin','full_name','email','instagram','youtube','score','feedback','website'];
  if(!p || typeof p!=='object' || Array.isArray(p) || Object.keys(p).some(k=>!keys.includes(k))) return false;
  if(typeof p.event_id!=='string' || !/^[a-z0-9-]{1,100}$/.test(p.event_id)) return false;
  if(typeof p.full_name!=='string' || !p.full_name.trim() || p.full_name.length>120 || /[\x00-\x1f\x7f]/.test(p.full_name)) return false;
  if(typeof p.email!=='string' || p.email.length>254 || /[\x00-\x1f\x7f]/.test(p.email)) return false;
  const email=p.email.trim();
  if(!/^[^\s@<>]+@[^\s@<>.]+(?:\.[^\s@<>.]+)+$/.test(email) || email.split('@')[0].length>64) return false;
  if(p.instagram!==true || p.youtube!==true || p.website!=='') return false;
  return typeof p.score==='string' && /^[1-5]$/.test(p.score) && typeof p.feedback==='string' && p.feedback.length<=300 && !/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(p.score+p.feedback);
}
function record_(p) {
  if(!validate_(p)) return 'invalid';
  const lock=LockService.getScriptLock(); if(!lock.tryLock(3000)) return 'retry';
  try {
    const event=event_(p.event_id); if(!event || !event.open) return 'closed';
    header_(event.tab,ATTENDANCE_HEADERS);
    const n=event.tab.getLastRow(); if(n>10000) return 'retry';
    const emails=n>1 ? event.tab.getRange(2,3,n-1,1).getValues() : [];
    if(emails.some(r=>normalizedEmail_(r[0])===normalizedEmail_(p.email))) return 'duplicate';
    const minute=String(Math.floor(Date.now()/60000)), rate=JSON.parse(props_().getProperty('RATE')||'{}');
    const count=rate.minute===minute ? rate.count : 0; if(count>=120) return 'retry';
    props_().setProperty('RATE',JSON.stringify({minute,count:count+1}));
    const now=new Date();
    const row=[Utilities.formatDate(now,'Asia/Jakarta','yyyy-MM-dd'),Utilities.formatDate(now,'Asia/Jakarta','HH:mm:ss'),safeCell_(p.email),safeCell_(p.full_name),'Y','Y',safeCell_(p.score),safeCell_(p.feedback),'Pending','','',''];
    if(n===event.tab.getMaxRows()) { event.tab.insertRowsAfter(n,100); formatTab_(event.tab); }
    const target=event.tab.getRange(n+1,1,1,12); target.setNumberFormat('@'); target.setValues([row]);
    event.tab.getRange(n+1,10).setNumberFormat('yyyy-mm-dd hh:mm');
    SpreadsheetApp.flush();
    // Acknowledgement follows a readback of persistence, never just dispatch.
    const saved=target.getValues()[0];
    if(normalizedEmail_(saved[2])!==normalizedEmail_(p.email) || saved[8]!=='Pending') return 'retry';
    return 'recorded';
  } finally { lock.releaseLock(); }
}
function correlation_(p) {
  return p && p.origin===SITE_ORIGIN && typeof p.event_id==='string' && /^[a-z0-9-]{1,100}$/.test(p.event_id) && /^[a-f0-9]{32}$/.test(p.request_id||'');
}
function ackKey_(p) { return 'ACK_'+p.event_id+'_'+p.request_id; }
function reply_(p,status) {
  if(!correlation_(p) || p.callback!=='baAttendance_'+p.request_id) return ContentService.createTextOutput('Request unavailable.');
  // Read-only JSONP returns only non-sensitive request status, never participant data.
  const message=JSON.stringify({type:'ba-attendance',request_id:p.request_id,event_id:p.event_id,status});
  return ContentService.createTextOutput(p.callback+'('+message+');').setMimeType(ContentService.MimeType.JAVASCRIPT);
}
function doGet(e) {
  const p=e && e.parameter; let status='closed';
  if(!correlation_(p)) return reply_(null,status);
  try {
    if(p.action==='ack') status=CacheService.getScriptCache().get(ackKey_(p))||'waiting';
    else if(p.action==='status') { const target=event_(p.event_id); if(target && target.open) status='open'; }
    else status='invalid';
  } catch(_) { status='retry'; }
  return reply_(p,status);
}
function doPost(e) {
  let p; let status='invalid';
  try {
    if(!e || !e.postData || e.postData.length>16000 || Object.keys(e.parameters).some(k=>k!=='payload') || !e.parameters.payload || e.parameters.payload.length!==1) return ContentService.createTextOutput('Request unavailable.');
    p=JSON.parse(e.parameter.payload);
    if(correlation_(p)) status=record_(p);
  } catch(_) {status='retry';}
  if(correlation_(p)) CacheService.getScriptCache().put(ackKey_(p),status,180);
  // This POST response is not treated as success. The browser reads its correlated acknowledgement.
  return ContentService.createTextOutput('Request processed. Return to the attendance page.');
}
