const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
function fixture(){const rows=[['Date Submitted','Time Submitted','Email','Material','Event','Download Status']],notes=new Map(),properties=new Map([['TRACKER_ID','fixture'],['DOWNLOAD_TAB_ID','7']]);let locked=false,fail=false;
const sheet={getName:()=> 'Download Material',getLastRow:()=>rows.length,getMaxRows:()=>1000,getRange:(r,c,n=1,w=1)=>({getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>rows[r-1+i]?.[c-1+j]??'')),getNotes:()=>Array.from({length:n},(_,i)=>[notes.get(r+i)||'']),setNote:s=>notes.set(r,s),setNumberFormat(){return this},setValues(v){assert(locked);if(fail){fail=false;throw Error('storage failure')}v.forEach((row,i)=>rows[r-1+i]=row.map(x=>typeof x==='string'&&x.startsWith("'")?x.slice(1):x));return this}})};
const ctx={PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)??null,setProperty:(k,v)=>properties.set(k,v)})},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;return true},releaseLock:()=>locked=false})},SpreadsheetApp:{openById:()=>({getSheetById:()=>sheet}),flush(){}},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_a,s)=>[...crypto.createHash('sha256').update(s).digest()],formatDate:(_d,tz,f)=>{assert.equal(tz,'Asia/Jakarta');return f==='yyyy-MM-dd'?'2026-09-18':'23:00:00'}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/backend.js','utf8')+'\n'+fs.readFileSync(__dirname+'/downloads.js','utf8'),ctx);const payload={action:'download',origin:'https://bamedicale.com',material_id:'current-diagnostic-approach-and-therapy-selection-for-thyroid-nodules',request_id:'a'.repeat(32),email:'qa@example.invalid'};return {ctx,rows,notes,payload,fail:()=>fail=true};}
test('download retries are idempotent but repeat intentional requests create new rows',()=>{const f=fixture();assert.equal(f.ctx.recordDownload_(f.payload),'recorded');assert.equal(f.ctx.recordDownload_(f.payload),'recorded');assert.equal(f.rows.length,2);assert.equal(f.ctx.recordDownload_({...f.payload,request_id:'b'.repeat(32)}),'recorded');assert.equal(f.rows.length,3);assert.equal(f.rows[1][0],'2026-09-18');assert.equal(f.rows[1][1],'23:00:00');assert.equal(f.rows[1][5],'Downloaded');assert.equal(f.ctx.recordDownload_({...f.payload,email:'other@example.invalid'}),'invalid');});
test('download input rejects unexpected fields, malformed values and client metadata',()=>{const f=fixture();for(const patch of [{email:'invalid'},{email:'a'.repeat(255)},{email:'a\nb@example.org'},{Material:'fake'},{Event:'fake'},{status:'fake'},{material_id:'unknown'},{request_id:'x'},{origin:'https://elsewhere.invalid'}])assert.equal(f.ctx.recordDownload_({...f.payload,...patch}),'invalid');assert.equal(f.rows.length,1);});
test('failed writes reserve the attempt and recover without collisions or duplicate rows',()=>{const f=fixture();f.fail();assert.throws(()=>f.ctx.recordDownload_(f.payload));assert.equal(f.rows.length,1);assert.equal(f.ctx.recordDownload_({...f.payload,request_id:'b'.repeat(32)}),'recorded');assert.equal(f.ctx.recordDownload_(f.payload),'recorded');assert.equal(f.rows.length,3);assert.equal(f.notes.size,2);assert.equal(f.ctx.recordDownload_(f.payload),'recorded');assert.equal(f.rows.length,3);});
test('formula-like email is stored as text and replay remains idempotent',()=>{const f=fixture();const p={...f.payload,email:'+qa@example.invalid'};assert.equal(f.ctx.recordDownload_(p),'recorded');assert.equal(f.ctx.recordDownload_(p),'recorded');assert.equal(f.rows.length,2);assert.equal(f.rows[1][2],p.email);});
test('new presentation downloads retain the correct material and reject cross-material replay',()=>{const f=fixture(),ids=['ultrasound-imaging-and-tirads-classification-in-thyroid-nodules','bethesda-system-for-reporting-thyroid-cytopathology'];for(const [i,id]of ids.entries()){const p={...f.payload,material_id:id,request_id:String(i+1).repeat(32)};assert.equal(f.ctx.recordDownload_(p),'recorded');assert.equal(f.ctx.recordDownload_(p),'recorded');assert.equal(f.ctx.recordDownload_({...p,material_id:ids[1-i]}),'invalid');}assert.equal(f.rows.length,3);assert.equal(f.rows[1][3],'Ultrasound Imaging and TIRADS Classification in Thyroid Nodules');assert.equal(f.rows[2][3],'Bethesda System for Reporting Thyroid Cytopathology');});
