(()=>{'use strict';
const model=window.BA_EBOOKS,registry=window.BAMEDICALE_REGISTRY.create(window.BAMEDICALE_DATA),books=registry.query({family:'ebook',publishedOnly:false}).map(r=>r.sourceRecord);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
const safePath=value=>{try{const u=new URL(value,location.origin+'/');return u.origin===location.origin||u.protocol==='https:'?u.href:'';}catch{return '';}};
const shelf=document.querySelector('[data-bookshelf]');
if(shelf){let batch=0;const draw=()=>{const state=model.batch(books,batch);batch=state.index;shelf.replaceChildren(...state.items.map(book=>{const a=node('a',null,'shelf-book');a.href='/ebooks/'+book.slug+'.html';const img=node('img');img.src=safePath(model.cover(book));img.alt=book.cover?'Cover of '+book.title:'BA Medicale default eBook cover';img.width=1086;img.height=1448;img.loading='lazy';const date=node('p','Published '),time=node('time',new Date(book.publishedDate+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}));time.dateTime=book.publishedDate;date.append(time);a.append(img,node('h2',book.title),date,node('span',book.state));return a;}));document.querySelector('[data-batch="prev"]').hidden=batch===0;document.querySelector('[data-batch="next"]').hidden=batch>=state.total-1;document.querySelector('[data-batch-status]').textContent=books.length?`${batch*25+1}–${Math.min((batch+1)*25,books.length)} of ${books.length} titles`:'New titles coming soon.';};document.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>{batch+=b.dataset.batch==='next'?1:-1;draw();shelf.querySelector('a')?.focus();});draw();return;}
const root=document.querySelector('[data-reader]');if(!root)return;const book=books.find(b=>b.slug===root.dataset.reader);if(!book)return;
const pages=model.pages(book),stage=root.querySelector('.reader-stage'),spread=root.querySelector('[data-spread]'),thumbs=root.querySelector('[data-thumbnails]'),accessible=root.querySelector('[data-accessible]'),status=root.querySelector('[data-reader-status]'),counter=root.querySelector('[data-counter]'),dialog=root.querySelector('dialog'),searchInput=root.querySelector('input[type=search]');
const controls=Object.fromEntries([...root.querySelectorAll('[data-action]')].map(b=>[b.dataset.action,b]));let page=0,zoom=1,mode='magazine',overview=false,turning=false;const mobile=matchMedia('(max-width:700px)'),reduced=matchMedia('(prefers-reduced-motion:reduce)');
const range=()=>model.spread(page,pages.length,!mobile.matches);const announce=t=>status.textContent=t;
function pageNode(p,index){const el=node('section',null,'book-page');el.setAttribute('aria-label','Page '+(index+1));if(p.image){const img=node('img');img.src=safePath(p.image);img.alt=p.title||'Book page '+(index+1);el.append(img);}else{const copy=node('div',null,'book-page__text');copy.append(node('small',book.demo?'Demonstration page':'BA Medicale'),node('h2',p.title||''),node('p',p.text||''));el.append(copy,node('footer',String(index+1)));}return el;}
function fit(){const r=range(),double=r.end>r.start;const width=Math.min(420,(stage.clientWidth-32)/(double?2:1))*zoom;spread.style.setProperty('--page-width',width+'px');spread.style.setProperty('--spread-width',width*(double?2:1)+'px');spread.classList.toggle('is-double',double);}
function draw(){const r=range();page=r.start;spread.replaceChildren(...pages.slice(r.start,r.end+1).map((p,i)=>pageNode(p,r.start+i)));for(const [dir,label] of [['prev','Previous page'],['next','Next page']]){const btn=node('button',null,'page-zone '+dir);btn.type='button';btn.setAttribute('aria-label',label);btn.disabled=dir==='prev'?page===0:r.end===pages.length-1;btn.onclick=()=>move(dir==='next'?1:-1);spread.append(btn);}counter.textContent=`${r.start===r.end?'Page '+(page+1):'Pages '+(page+1)+'–'+(r.end+1)} / ${pages.length}`;controls.prev.disabled=page===0||mode!=='magazine'||overview;controls.next.disabled=r.end===pages.length-1||mode!=='magazine'||overview;fit();}
function move(direction){if(turning||mode!=='magazine'||overview)return;const r=range();const target=direction>0?r.end+1:r.start-1;if(target<0||target>=pages.length)return;const outgoing=spread.querySelectorAll('.book-page')[direction>0?r.end-r.start:0]?.cloneNode(true);page=target;draw();if(!reduced.matches&&outgoing){turning=true;outgoing.classList.add('turning-sheet');if(direction<0)outgoing.classList.add('reverse');outgoing.setAttribute('aria-hidden','true');outgoing.style.left=direction>0&&r.end>r.start?'50%':'0';spread.append(outgoing);setTimeout(()=>{outgoing.remove();turning=false;},470);}}
function showMode(){stage.hidden=mode!=='magazine'||overview;thumbs.hidden=!overview;accessible.hidden=mode!=='accessible'||overview;controls.view.setAttribute('aria-pressed',String(mode==='accessible'));controls.view.setAttribute('aria-label',mode==='accessible'?'Switch to Magazine View':'Switch to Accessible View');controls.view.title=controls.view.getAttribute('aria-label');controls.grid.setAttribute('aria-pressed',String(overview));root.querySelector('.reader-mode').textContent=mode==='accessible'?'Accessible View':'Magazine View';root.querySelector('.reader-hint').hidden=mode!=='magazine'||overview;['minus','plus','reset'].forEach(k=>controls[k].disabled=mode!=='magazine'||overview);draw();}
function thumbnails(){thumbs.replaceChildren(...pages.map((p,i)=>{const b=node('button');b.type='button';b.setAttribute('aria-label','Open page '+(i+1));if(p.image){const img=node('img');img.src=safePath(p.image);img.alt='';b.append(img);}else b.append(node('span',p.title||'Page '+(i+1),'preview-thumb'));b.append(node('small','Page '+(i+1)));b.onclick=()=>{page=i;overview=false;mode='magazine';showMode();stage.focus();};return b;}));}
if(!book.demo){accessible.replaceChildren(node('h2',book.title));for(const p of pages.slice(1)){const section=node('section');section.append(node('h3',p.title||''),node('p',p.text||'Text is not yet available for this page.'));accessible.append(section);}}
function stored(action){try{return localStorage.getItem('ba-ebook:'+book.id+':'+action)==='true';}catch{return false;}}
for(const action of ['like','favorite'])controls[action].setAttribute('aria-pressed',String(stored(action)));
controls.prev.onclick=()=>move(-1);controls.next.onclick=()=>move(1);
for(const [action,delta] of [['minus',-.25],['plus',.25],['reset',0]])controls[action].onclick=()=>{zoom=delta?Math.min(2,Math.max(.75,zoom+delta)):1;controls.reset.textContent=Math.round(zoom*100)+'%';fit();};
controls.grid.onclick=()=>{overview=!overview;if(overview)thumbnails();showMode();};controls.view.onclick=()=>{mode=mode==='magazine'?'accessible':'magazine';overview=false;showMode();};
controls.search.onclick=()=>{searchInput.disabled=!!book.demo;root.querySelector('[data-search-status]').textContent=book.demo?'Search will be available with published content':'Search the available page text.';dialog.showModal();};searchInput.oninput=()=>{const results=model.search(book,searchInput.value);root.querySelector('[data-search-status]').textContent=results.length+' matching pages';root.querySelector('[data-search-results]').replaceChildren(...results.map(r=>{const li=node('li'),b=node('button','Page '+(r.index+1)+' · '+r.title);b.onclick=()=>{page=r.index;mode='magazine';overview=false;dialog.close();showMode();stage.focus();};li.append(b);return li;}));};
controls.fullscreen.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(root.requestFullscreen)await root.requestFullscreen();else announce('Fullscreen is unavailable here. You can use your browser’s fullscreen control.');}catch{announce('Fullscreen is unavailable here. You can use your browser’s fullscreen control.');}};document.addEventListener('fullscreenchange',()=>{controls.fullscreen.title=document.fullscreenElement?'Exit fullscreen':'Fullscreen';controls.fullscreen.setAttribute('aria-label',controls.fullscreen.title);fit();});
controls.share.onclick=async()=>{const url=document.querySelector('link[rel=canonical]').href;try{if(navigator.share&&matchMedia("(pointer:coarse)").matches)await navigator.share({title:book.title,url});else{await navigator.clipboard.writeText(url);announce('Reader link copied.');}}catch(e){if(e.name!=='AbortError'){announce('Copy this reader link: '+url);}}};
for(const action of ['like','favorite'])controls[action].onclick=()=>{const active=controls[action].getAttribute('aria-pressed')!=='true';controls[action].setAttribute('aria-pressed',String(active));try{localStorage.setItem('ba-ebook:'+book.id+':'+action,String(active));announce((active?'Saved':'Removed')+' on this browser only.');}catch{announce('Updated for this visit. Browser storage is unavailable.');}};
root.addEventListener('keydown',e=>{if(dialog.open||e.target.matches('input,textarea,select')||mode!=='magazine'||overview)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}});
let touch;stage.addEventListener('touchstart',e=>{touch=e.touches.length===1&&zoom===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null;},{passive:true});stage.addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5)move(dx<0?1:-1);touch=null;},{passive:true});
mobile.addEventListener('change',draw);window.addEventListener('resize',fit);draw();
})();
