(() => {
  "use strict";
  const cfg = window.JUMI_CONFIG || {};
  const httpsRoot = "https:"+"/"+"/";
  const modules = ["Dashboard","Events","Registrants","Payments","Attendance","Notifications","Certificates","Community","Reports","Settings"];
  const descriptions = {
    Dashboard:"Seminar operations at a glance.", Events:"Create, prepare, preview, and manage seminar records.", Registrants:"Independent registration, payment, confirmation, attendance, and certificate states.", Payments:"Validate transfers and preserve private payment evidence.", Attendance:"Reconcile BA Medicale, LMS, manual, and future Zoom evidence.", Notifications:"Prepare messages and schedules without simulating delivery.", Certificates:"Review eligibility before generation, approval, or sending.", Community:"A careful longitudinal view of doctor engagement.", Reports:"Operational trends backed only by stored data.", Settings:"Administrators, integrations, and safe defaults."
  };
  const state = {admin:null,data:null,view:"Dashboard",scope:"all",filters:{query:"",status:"all"}};
  const $ = (s,root=document) => root.querySelector(s);
  const esc = value => String(value ?? "").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const fmt = value => value==null?"—":Number(value || 0).toLocaleString("en-US");
  const dateText = value => value ? new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeZone:cfg.timezone||"Asia/Jakarta"}).format(new Date(value)) : "Not available";
  const statusClass = value => /paid|registered|sent|delivered|attended|eligible|connected|published/i.test(value)?"good":/pending|submitted|queued|not sent|not checked|draft/i.test(value)?"wait":/failed|cancelled|not attended|denied/i.test(value)?"bad":"";
  const status = value => `<span class="status ${statusClass(value)}">${esc(value || "Not available")}</span>`;
  const empty = text => `<div class="empty"><strong>No data yet</strong><p>${esc(text)}</p></div>`;
  const currentEvents = () => {
    const events = state.data?.events || [];
    if(state.scope === "all") return events;
    return events.filter(event => String(event.lifecycle || "").toLowerCase() === state.scope);
  };
  const registrants = () => {
    const allowed = new Set(currentEvents().map(event=>event.id));
    return (state.data?.registrants || []).filter(row => state.scope === "all" || allowed.has(row.eventId));
  };
  const integration = name => state.data?.integrations?.[name] || "Not Connected";
  const calendarUrl = event => {const stamp=value=>new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const details=[event.description,event.format==="Online"?event.meetingUrl:event.address,event.publicUrl].filter(Boolean).join("\n\n");return httpsRoot+"calendar.google.com/calendar/render?"+new URLSearchParams({action:"TEMPLATE",text:event.title||"BA Medicale Seminar",dates:`${stamp(event.startAt)}/${stamp(event.endAt)}`,details,location:event.format==="Online"?(event.platform||"Online"):([event.venue,event.address].filter(Boolean).join(", ")),ctz:"Asia/Jakarta"}).toString();};
  function downloadIcs(event){const stamp=value=>new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const safe=value=>String(value||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");const productId=["PRODID:-","/","/BA Medicale","/","/JUMI Seminar OS","/","/EN"].join("");const lines=["BEGIN:VCALENDAR","VERSION:2.0",productId,"CALSCALE:GREGORIAN","BEGIN:VEVENT",`UID:${safe(event.id)}@bamedicale.com`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(event.startAt)}`,`DTEND:${stamp(event.endAt)}`,`SUMMARY:${safe(event.title)}`,`DESCRIPTION:${safe([event.description,event.meetingUrl,event.publicUrl].filter(Boolean).join("\n\n"))}`,`LOCATION:${safe(event.format==="Online"?(event.platform||"Online"):[event.venue,event.address].filter(Boolean).join(", "))}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([lines],{type:"text/calendar;charset=utf-8"}));link.download=`${event.id||"ba-medicale-seminar"}.ics`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}

  function setGate(message,isError=false){const el=$("#gate-status");el.textContent=message;el.style.color=isError?"#a52a3d":"";}
  function request(action,data={}){
    if(!window.JUMI_SERVER_MODE || !window.google?.script?.run) return Promise.reject(new Error("Secure backend is not configured."));
    return new Promise((resolve,reject)=>{
      google.script.run.withSuccessHandler(resolve).withFailureHandler(error=>reject(new Error(error?.message||"The secure backend did not respond."))).jumiApi(`jumi_${action}`,data);
    });
  }
  async function initializeAuth(){
    if(window.JUMI_SERVER_MODE){
      setGate("Verifying the signed-in Google account with JUMI…");
      try{const data=await request("bootstrap");state.admin=data.admin;state.data=data;openApp();}catch(error){setGate(error.message||"Access denied.",true);}
      return;
    }
    if(!cfg.secureAppUrl){$("#setup-disabled").hidden=false;setGate("The private JUMI Google deployment is not connected. No operational data is exposed.");return;}
    const launch=$("#secure-launch");launch.href=cfg.secureAppUrl;launch.hidden=false;setGate("Continue to Google to sign in. JUMI checks the private admin allowlist before loading data.");
  }
  function openApp(){
    $("#secure-gate").hidden=true;$("#app-shell").hidden=false;$("#admin-identity").textContent=state.admin?.email||"Authorized admin";
    $("#primary-nav").innerHTML=modules.map((name,i)=>`<button type="button" data-view="${name}" ${i===0?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${["◫","◇","◎","▣","✓","✉","▤","◉","▥","⚙"][i]}</span>${name}</button>`).join("");
    render();
  }
  function showBanner(message){const el=$("#system-banner");el.textContent=message;el.hidden=!message;}
  function navigate(name){state.view=name;$("#view-title").textContent=name;$("#view-description").textContent=descriptions[name];document.querySelectorAll("[data-view]").forEach(btn=>btn.setAttribute("aria-current",btn.dataset.view===name?"page":"false"));$("#sidebar").classList.remove("open");$("#nav-toggle").setAttribute("aria-expanded","false");render();}
  function render(){const fn={Dashboard:dashboard,Events:eventsView,Registrants:registrantsView,Payments:paymentsView,Attendance:attendanceView,Notifications:notificationsView,Certificates:certificatesView,Community:communityView,Reports:reportsView,Settings:settingsView}[state.view];$("#view").innerHTML=fn();bindView();}
  function metric(label,value,note=""){const detail=note||(value==null?"No data yet":"");return `<article class="kpi"><span>${esc(label)}</span><strong>${fmt(value)}</strong>${detail?`<small>${esc(detail)}</small>`:""}</article>`;}
  function dashboard(){
    const m=state.data?.metrics||{},flow=state.data?.funnel||{};
    return `<div class="kpi-grid">${[["Total Events",m.totalEvents],["Upcoming Events",m.upcomingEvents],["Total Doctors",m.totalDoctors],["Active Doctors",m.activeDoctors],["Total Registrations",m.totalRegistrations],["Registered",m.registered],["Paid",m.paid],["Pending Payment",m.pendingPayment],["Confirmations Sent",m.confirmationsSent],["Attendance",m.attended],["Quiz Participants",m.quizParticipants],["Material Downloads",m.materialDownloads],["Certificate Eligible",m.certificateEligible],["Certificates Sent",m.certificatesSent]].map(x=>metric(...x)).join("")}</div>
    <div class="grid-2"><section class="panel"><div class="panel-header"><div><h2>Participant funnel</h2><p>Independent states, counted from persisted records.</p></div></div><div class="funnel">${[["Submitted",flow.submitted],["Paid / Not Required",flow.paymentReady],["Registered",flow.registered],["Confirmation Sent",flow.confirmed],["Attended",flow.attended],["Certificate Eligible",flow.eligible],["Certificate Sent",flow.sent]].map(([label,value])=>`<div><b>${fmt(value)}</b><span>${label}</span></div>`).join("")}</div></section>
    <section class="panel"><div class="panel-header"><div><h2>Operational health</h2><p>Provider and storage readiness.</p></div></div>${["sheets","drive","email","whatsapp","publisher"].map(name=>`<div class="provider-state"><span>${name[0].toUpperCase()+name.slice(1)}</span>${status(integration(name))}</div>`).join("")}</section></div>
    <div class="grid-2"><section class="panel"><div class="panel-header"><div><h2>Active events</h2><p>Current event scope: ${esc(state.scope)}.</p></div><button class="button button-secondary" data-view="Events">Open Events</button></div>${eventRows(currentEvents().slice(0,4))}</section><section class="panel"><h2>Signals</h2>${(state.data?.insights||[]).length?`<div class="chart-bars">${state.data.insights.map(row=>`<div><span>${esc(row.label)}</span><span class="bar"><i style="width:${Math.min(100,Number(row.percent)||0)}%"></i></span><b>${esc(row.value)}</b></div>`).join("")}</div>`:empty("Historical comparisons appear when enough source data exists.")}</section></div>`;
  }
  function eventRows(rows){return rows.length?`<div class="event-list">${rows.map(event=>`<article class="event-row"><div><h3>${esc(event.title)}</h3><p>${esc(event.dateLabel||dateText(event.startAt))} · ${esc(event.format||"Not available")} · ${esc(event.commercial||"Not available")}</p></div>${status(event.lifecycle||"Draft")}<div class="event-actions"><button class="button button-secondary" data-calendar="${esc(event.id)}">Google Calendar</button><button class="button button-secondary" data-ics="${esc(event.id)}">.ics</button><button class="button button-secondary" data-event="${esc(event.id)}">Manage</button></div></article>`).join("")}</div>`:empty("No events match this scope.");}
  function eventsView(){const selected=currentEvents()[0],tools=selected?state.data?.toolsByEvent?.[selected.id]||{}:{};return `<section class="panel"><div class="panel-header"><div><h2>Seminars</h2><p>One event record drives operations, tools, calendars, and publication preparation.</p></div><button class="button button-primary" data-action="new-event">Create Seminar</button></div>${eventRows(currentEvents())}</section><section class="panel"><div class="panel-header"><div><h2>Generation pipeline</h2><p>Generate → Preview → Publish. Production publishing stays blocked until the secure GitHub publisher is connected.</p></div>${status(integration("publisher"))}</div><div class="module-grid">${["Public event page","Listing and homepage","Registration + permanent QR","Google Calendar + .ics","Admin workspace","Event Tools container"].map(name=>`<article class="module-card"><h3>${name}</h3><p>Prepared from the canonical event record without duplicate event data.</p><button class="button" disabled>Preview after event selection</button></article>`).join("")}</div></section><section class="panel"><div class="panel-header"><div><h2>Event Tools${selected?` — ${esc(selected.title)}`:""}</h2><p>Live counts come from the current tracker compatibility layer; unavailable modules remain explicit.</p></div></div><div class="module-grid">${[["Registration",tools.registrants],["Attendance",tools.attendance],["LMS Attendance",null],["BA Medicale Live Quiz",tools.baQuiz],["LMS Live Quiz",tools.lmsQuiz],["Presentations",null],["Materials",state.data?.metrics?.materialDownloads],["eBooks",null],["Certificates",tools.certificates]].map(([name,value])=>`<article class="module-card"><h3>${name}</h3><p>${value==null?"No mapped data yet.":`${fmt(value)} mapped record${Number(value)===1?"":"s"}.`}</p>${status(value==null?"Not available":"Connected")}</article>`).join("")}</div></section>`;}
  function filteredRegistrants(){const q=state.filters.query.toLowerCase();return registrants().filter(row=>(!q||`${row.name} ${row.email} ${row.whatsapp}`.toLowerCase().includes(q))&&(state.filters.status==="all"||Object.values(row).includes(state.filters.status)));}
  function registrantTable(rows){return rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th><input type="checkbox" aria-label="Select all filtered"></th><th>Name</th><th>Email</th><th>Seminar</th><th>Registration</th><th>Payment</th><th>Confirmation</th><th>Attendance</th><th>Certificate</th><th></th></tr></thead><tbody>${rows.map(row=>`<tr><td><input type="checkbox" aria-label="Select ${esc(row.name)}"></td><td>${esc(row.name||"Not available")}</td><td>${esc(row.email)}</td><td>${esc(row.eventTitle||row.eventId)}</td><td>${status(row.registrationStatus)}</td><td>${status(row.paymentStatus)}</td><td>${status(row.confirmationStatus)}</td><td>${status(row.attendanceStatus)}</td><td>${status(row.certificateStatus)}</td><td><button class="button button-secondary" data-participant="${esc(row.id)}">Details</button></td></tr>`).join("")}</tbody></table></div>`:empty("No registrants match the current event scope and filters.");}
  function registrantsView(){return `<section class="panel"><div class="panel-header"><div><h2>Registrants</h2><p>Statuses stay independent and bulk actions apply only to the filtered selection.</p></div></div><div class="toolbar"><input id="registrant-search" type="search" placeholder="Search name, email, or WhatsApp" value="${esc(state.filters.query)}"><select id="registrant-status"><option value="all">All statuses</option>${["Submitted","Registered","Paid","Pending","Not Required","Not Sent","Failed","Attended","Eligible"].map(v=>`<option ${state.filters.status===v?"selected":""}>${v}</option>`).join("")}</select><button class="button" disabled>Bulk actions</button></div>${registrantTable(filteredRegistrants())}</section>`;}
  function paymentsView(){const rows=registrants().filter(r=>r.paymentStatus!=="Not Required");return `<section class="panel"><div class="panel-header"><div><h2>Payment validation</h2><p>Evidence upload never marks a payment as paid. Confirmation is a separate audited action.</p></div>${status(integration("drive"))}</div>${rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Participant</th><th>Event</th><th>Status</th><th>Amount</th><th>Payment date</th><th>Evidence</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name||r.email)}</td><td>${esc(r.eventTitle||r.eventId)}</td><td>${status(r.paymentStatus)}</td><td>${r.paymentAmount?`${esc(r.currency||"IDR")} ${fmt(r.paymentAmount)}`:"Not available"}</td><td>${esc(r.paymentDate||"Not available")}</td><td>${r.proofReference?"Private file stored":"Not uploaded"}</td><td><button class="button" data-payment="${esc(r.id)}">Review</button></td></tr>`).join("")}</tbody></table></div>`:empty("No paid-seminar payment records are available.")}</section>`;}
  function attendanceView(){return `<section class="panel"><div class="panel-header"><div><h2>Attendance workspace</h2><p>Registration and attendance remain separate; Zoom presence alone never implies certificate eligibility.</p></div></div><div class="kpi-grid">${[["Registered",state.data?.metrics?.registered],["Attendance checked",state.data?.metrics?.attendanceChecked],["Attended",state.data?.metrics?.attended],["Not attended",state.data?.metrics?.notAttended],["Pending validation",state.data?.metrics?.attendancePending]].map(x=>metric(...x)).join("")}</div></section><section class="panel"><h2>Inputs</h2><div class="module-grid">${[["BA Medicale Attendance","Connected"],["LMS Attendance","Connected"],["Manual / Imported","Available"],["Zoom report","Not Connected"]].map(([a,b])=>`<article class="module-card"><h3>${a}</h3><p>${b==="Connected"?"Mapped through the existing tracker compatibility layer.":"Prepared for future reconciliation."}</p>${status(b)}</article>`).join("")}</div></section>`;}
  function notificationsView(){return `<section class="panel"><div class="panel-header"><div><h2>Notification Center</h2><p>Prepare recipients, language, wording, and recommended schedules before providers are connected.</p></div></div><div class="module-grid"><article class="module-card"><h3>Email</h3><p>Registration, reminders, thank-you, certificate, and custom templates.</p>${status("Not Connected")}</article><article class="module-card"><h3>WhatsApp</h3><p>Meta/provider credentials are intentionally absent.</p>${status("Not Connected")}</article><article class="module-card"><h3>Recommended schedules</h3><p>H-1 Day and H-1 Hour derive from the canonical event start in Asia/Jakarta.</p>${status("Available")}</article></div></section><section class="panel"><div class="form-grid"><div class="field"><label>Channel</label><select><option>Email</option><option>WhatsApp</option><option>Both</option></select></div><div class="field"><label>Language</label><select><option>Bahasa Indonesia</option><option>English</option></select></div><div class="field"><label>Template</label><select>${["Registration Received / Payment Pending","Registration Confirmation","H-1 Day","H-1 Hour","Starting Soon","Thank You","Certificate","Custom"].map(v=>`<option>${v}</option>`).join("")}</select></div><div class="field"><label>Schedule</label><input value="Recommended — choose an event" readonly></div><div class="field full"><label>Message preview</label><textarea placeholder="Choose an event and template. Missing factual values remain pending."></textarea></div></div><div class="dialog-actions"><button class="button" disabled>Schedule — Provider Not Connected</button><button class="button button-primary" disabled>Send Now — Provider Not Connected</button></div></section>`;}
  function certificatesView(){return `<section class="panel"><div class="panel-header"><div><h2>Certificate review</h2><p>Attendance validation → eligibility → admin review → generate → approve → send.</p></div></div><div class="funnel">${[["Not Eligible",state.data?.metrics?.certificateNotEligible],["Eligible",state.data?.metrics?.certificateEligible],["Generated",state.data?.metrics?.certificateGenerated],["Approved",state.data?.metrics?.certificateApproved],["Sent",state.data?.metrics?.certificatesSent],["Failed",state.data?.metrics?.certificateFailed]].map(([a,b])=>`<div><b>${fmt(b)}</b><span>${a}</span></div>`).join("")}</div><p class="status-note">BA Medicale participation certificates remain separate from official SKP/LMS certificates. Generation is disabled until eligibility rules are configured.</p></section>`;}
  function communityView(){const rows=state.data?.community||[];return `<section class="panel"><div class="panel-header"><div><h2>Doctor community</h2><p>Normalized email supports careful aggregation without merging uncertain identities.</p></div></div>${rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Email</th><th>Registered</th><th>Attended</th><th>Quiz</th><th>Downloads</th><th>First seen</th><th>Last engagement</th><th>Type</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.email)}</td><td>${fmt(r.eventsRegistered)}</td><td>${fmt(r.eventsAttended)}</td><td>${fmt(r.quizParticipation)}</td><td>${fmt(r.downloads)}</td><td>${esc(r.firstSeen||"Not available")}</td><td>${esc(r.lastEngagement||"Not available")}</td><td>${status(r.returning?"Returning":"New")}</td></tr>`).join("")}</tbody></table></div>`:empty("Community profiles appear after safely identifiable participant records are mapped.")}</section>`;}
  function reportsView(){const r=state.data?.reports||{};return `<div class="kpi-grid">${[["Registration → Attendance",r.registrationAttendancePercent,"%"],["Free events",r.freeEvents],["Paid events",r.paidEvents],["Repeat attendees",r.repeatAttendees],["Quiz participation",r.quizParticipation],["Material downloads",r.materialDownloads]].map(([a,b,c])=>metric(a,b,c)).join("")}</div><div class="grid-2"><section class="panel"><h2>Event-over-event</h2>${(r.eventComparison||[]).length?`<div class="chart-bars">${r.eventComparison.map(x=>`<div><span>${esc(x.label)}</span><span class="bar"><i style="width:${Math.min(100,x.percent)}%"></i></span><b>${fmt(x.value)}</b></div>`).join("")}</div>`:empty("No comparable historical series yet.")}</section><section class="panel"><h2>Monthly trend</h2>${r.monthOverMonth==null?empty("MoM appears after sufficient monthly data exists."):`<p><strong>${esc(r.monthOverMonth)}%</strong> month over month</p>`}</section></div>`;}
  function settingsView(){return `<div class="grid-2"><section class="panel"><h2>Authorized admins</h2><p>Allowlist enforcement is server-side. Frontend identity is never trusted.</p><div class="provider-state"><span>${esc(state.admin?.email||"Authorized admin")}</span>${status(state.admin?.role||"Owner")}</div></section><section class="panel"><h2>Defaults</h2><div class="provider-state"><span>Timezone</span><b>Asia/Jakarta</b></div><div class="provider-state"><span>Notification language</span><b>Bahasa Indonesia</b></div></section></div><section class="panel"><h2>Integrations</h2><div class="module-grid">${[["Google Sheets",integration("sheets")],["Google Drive",integration("drive")],["Email Provider","Not Connected"],["WhatsApp / Meta","Not Connected"],["GitHub Publisher",integration("publisher")]].map(([a,b])=>`<article class="module-card"><h3>${a}</h3><p>No credentials are displayed in JUMI.</p>${status(b)}</article>`).join("")}</div></section>`;}
  function eventForm(event={}){event={...event,date:event.date||String(event.startAt||"").slice(0,10),startTime:event.startTime||String(event.startAt||"").slice(11,16),endTime:event.endTime||String(event.endAt||"").slice(11,16)};return `<h2>${event.id?"Edit":"Create"} Seminar</h2><p>Missing facts may remain pending. JUMI never invents seminar details.</p><div class="form-grid"><fieldset class="fieldset"><legend>Basic</legend></fieldset>${field("title","Seminar Title",event.title,"text",true)}${field("subtitle","Subtitle / Theme",event.subtitle)}${field("date","Date",event.date,"date",true)}${field("startTime","Start Time",event.startTime,"time",true)}${field("endTime","End Time",event.endTime,"time",true)}${field("registrationOpen","Registration Open",event.registrationOpen,"datetime-local")}${field("registrationClose","Registration Close",event.registrationClose,"datetime-local")}<fieldset class="fieldset"><legend>Format and commercial</legend></fieldset>${selectField("format","Format",["Online","Offline"],event.format)}${field("platform","Platform / Venue",event.platform||event.venue)}${field("meetingUrl","Meeting/Event URL",event.meetingUrl,"url")}${field("address","Full Address",event.address)}${selectField("commercial","Commercial",["Free","Paid"],event.commercial)}${field("price","Price",event.price,"number")}${field("currency","Currency",event.currency||"IDR")}<fieldset class="fieldset"><legend>Content</legend></fieldset>${field("speakers","Speakers and roles",event.speakers,"textarea")}${field("description","Seminar description / source information",event.description,"textarea")}${field("audience","Audience",event.audience)}${field("capacity","Capacity",event.capacity,"number")}${field("skp","SKP information",event.skp)}${field("lms","LMS information",event.lms)}${field("posterReference","Approved poster reference",event.posterReference)}<div class="field full"><label>Publication</label><p>Generate and Preview may be prepared after save. Publish remains blocked until the secure publisher is connected.</p></div></div><div class="dialog-actions"><button class="button" value="cancel">Cancel</button><button class="button button-primary" type="button" data-save-event data-id="${esc(event.id||"")}">Save Seminar</button></div>`;}
  function field(name,label,value="",type="text",required=false){const area=type==="textarea";return `<div class="field ${area?"full":""}"><label for="f-${name}">${label}${required?" *":""}</label>${area?`<textarea id="f-${name}" name="${name}">${esc(value)}</textarea>`:`<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${required?"required":""}>`}</div>`;}
  function selectField(name,label,options,value){return `<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options.map(v=>`<option ${v===value?"selected":""}>${v}</option>`).join("")}</select></div>`;}
  function openDialog(html){$("#dialog-content").innerHTML=html;$("#dialog").showModal();bindDialog();}
  function bindDialog(){
    $("[data-save-event]")?.addEventListener("click",async event=>{const button=event.currentTarget,fields=[...$("#dialog-content").querySelectorAll("input,select,textarea")];const data=Object.fromEntries(fields.map(el=>[el.name,el.value.trim()]));data.id=button.dataset.id||undefined;button.disabled=true;button.textContent="Saving…";try{await request("save_event",data);state.data=await request("bootstrap");$("#dialog").close();showBanner("Seminar saved to the structured tracker.");render();}catch(error){showBanner(error.message);button.disabled=false;button.textContent="Save Seminar";}});
    $("[data-mark-paid]")?.addEventListener("click",async event=>{const button=event.currentTarget;if(!confirm("Confirm this payment as received? This audited action will set Payment to Paid and Registration to Registered."))return;button.disabled=true;try{await request("mark_paid",{registrantId:button.dataset.markPaid,amount:$("#f-amount").value,paymentDate:$("#f-paymentDate").value,notes:$("#f-notes").value});state.data=await request("bootstrap");$("#dialog").close();showBanner("Payment persisted and audited.");render();}catch(error){showBanner(error.message);button.disabled=false;}});
    $("[data-proof-input]")?.addEventListener("change",async event=>{const input=event.currentTarget,file=input.files?.[0];if(!file)return;if(file.size>5*1024*1024){showBanner("Use a JPG, PNG, or PDF no larger than 5 MB.");input.value="";return;}input.disabled=true;try{const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",").pop());reader.onerror=reject;reader.readAsDataURL(file);});await request("upload_proof",{registrantId:input.dataset.id,mimeType:file.type,base64});state.data=await request("bootstrap");$("#dialog").close();showBanner("Private payment evidence stored. Payment status was not changed.");render();}catch(error){showBanner(error.message);input.disabled=false;}});
    $("[data-view-proof]")?.addEventListener("click",async event=>{const button=event.currentTarget;button.disabled=true;try{const result=await request("get_proof_url",{registrantId:button.dataset.viewProof});window.open(result.url,"_blank","noopener");}catch(error){showBanner(error.message);button.disabled=false;}});
  }
  function participantDetail(row){return `<h2>${esc(row.name||row.email)}</h2><p>${esc(row.eventTitle||row.eventId)}</p><div class="module-grid">${[["Registration",row.registrationStatus],["Payment",row.paymentStatus],["Confirmation",row.confirmationStatus],["Attendance",row.attendanceStatus],["Certificate",row.certificateStatus]].map(([a,b])=>`<div class="module-card"><h3>${a}</h3>${status(b)}</div>`).join("")}</div><p>Email: ${esc(row.email)}<br>WhatsApp: ${esc(row.whatsapp||"Not available")}</p>`;}
  function paymentDetail(row){return `<h2>Review payment</h2><p>${esc(row.name||row.email)} · ${esc(row.eventTitle||row.eventId)}</p><div class="form-grid">${field("amount","Payment amount",row.paymentAmount,"number",true)}${field("paymentDate","Payment date",row.paymentDate,"date",true)}${field("notes","Notes",row.paymentNotes,"textarea")}<div class="field full"><label>Payment evidence</label><p>${row.proofReference?"A private Drive file reference exists.":"No proof uploaded."} Uploading or replacing evidence does not mark the payment paid.</p><input type="file" data-proof-input data-id="${esc(row.id)}" accept="image/jpeg,image/png,application/pdf" ${integration("drive")!=="Connected"?"disabled":""}>${row.proofReference?`<button class="button button-secondary" type="button" data-view-proof="${esc(row.id)}">View Proof</button>`:""}</div></div><div class="dialog-actions"><button class="button" value="cancel">Cancel</button><button class="button button-primary" type="button" data-mark-paid="${esc(row.id)}">Mark as Paid</button></div>`;}
  function bindView(){
    document.querySelectorAll("[data-view]").forEach(el=>el.addEventListener("click",()=>navigate(el.dataset.view)));
    document.querySelectorAll("[data-action='new-event']").forEach(el=>el.addEventListener("click",()=>openDialog(eventForm())));
    document.querySelectorAll("[data-event]").forEach(el=>el.addEventListener("click",()=>{const row=(state.data.events||[]).find(x=>x.id===el.dataset.event);openDialog(eventForm(row||{}));}));
    document.querySelectorAll("[data-participant]").forEach(el=>el.addEventListener("click",()=>openDialog(participantDetail((state.data.registrants||[]).find(x=>x.id===el.dataset.participant)||{}))));
    document.querySelectorAll("[data-payment]").forEach(el=>el.addEventListener("click",()=>openDialog(paymentDetail((state.data.registrants||[]).find(x=>x.id===el.dataset.payment)||{}))));
    document.querySelectorAll("[data-calendar]").forEach(el=>el.addEventListener("click",()=>{const event=(state.data.events||[]).find(x=>x.id===el.dataset.calendar);if(event)window.open(calendarUrl(event),"_blank","noopener");}));
    document.querySelectorAll("[data-ics]").forEach(el=>el.addEventListener("click",()=>{const event=(state.data.events||[]).find(x=>x.id===el.dataset.ics);if(event)downloadIcs(event);}));
    $("#registrant-search")?.addEventListener("input",event=>{state.filters.query=event.target.value;render();});
    $("#registrant-status")?.addEventListener("change",event=>{state.filters.status=event.target.value;render();});
  }
  $("#event-scope").addEventListener("change",event=>{state.scope=event.target.value;render();});
  $("#primary-nav").addEventListener("click",event=>{const button=event.target.closest("[data-view]");if(button)navigate(button.dataset.view);});
  $("#nav-toggle").addEventListener("click",()=>{const open=$("#sidebar").classList.toggle("open");$("#nav-toggle").setAttribute("aria-expanded",String(open));});
  $("#signout").addEventListener("click",()=>{state.admin=null;state.data=null;if(window.JUMI_SERVER_MODE){window.top.location.href=httpsRoot+"bamedicale.com/jumi/";return;}$("#app-shell").hidden=true;$("#secure-gate").hidden=false;setGate("Signed out. Sign in again to continue.");});
  if(location.hostname==="127.0.0.1" && new URLSearchParams(location.search).has("qa")){
    state.admin={email:"qa@example.invalid",role:"QA"};
    state.data={admin:state.admin,events:[{id:"management-thyroid-nodules-2026",title:"Management of Thyroid Nodules — How to Make a Good Diagnosis?",startAt:"2026-09-19T09:00:00+07:00",format:"Online",commercial:"Free",lifecycle:"Completed"}],registrants:[],community:[],metrics:{totalEvents:1,upcomingEvents:0,totalDoctors:0,activeDoctors:0,totalRegistrations:0,registered:0,paid:0,pendingPayment:0,confirmationsSent:0,attended:0,attendanceChecked:0,notAttended:0,attendancePending:0,certificateEligible:0,certificatesSent:0},funnel:{},reports:{},insights:[],integrations:{sheets:"Connected",drive:"Connected",email:"Not Connected",whatsapp:"Not Connected",publisher:"Not Connected"}};
    openApp();
  }else initializeAuth();
})();
