(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.JUMI_CONTENT_OS=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  const TZ="Asia/Jakarta",DAY=86400000,RULES={Seminar:{label:"A4 portrait",ratio:1/Math.sqrt(2),tolerance:.02},Article:{label:"16:9 landscape",ratio:16/9,tolerance:.02},eBook:{label:"3:4 portrait",ratio:3/4,tolerance:.02}};
  const parts=(value,options={})=>Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit",...options}).formatToParts(new Date(value)).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));
  const dayKey=value=>{if(!Number.isFinite(new Date(value).getTime()))return"";const p=parts(value);return `${p.year}-${p.month}-${p.day}`;};
  const monthKey=value=>dayKey(value).slice(0,7);
  const mondayKey=value=>{const date=new Date(`${dayKey(value)}T00:00:00+07:00`),weekday=Number(new Intl.DateTimeFormat("en-US",{timeZone:TZ,weekday:"short"}).formatToParts(date).find(p=>p.type==="weekday")?.value==="Sun"?0:date.getDay());date.setTime(date.getTime()-((weekday+6)%7)*DAY);return dayKey(date);};
  const stamp=value=>{const n=Date.parse(value||"");return Number.isFinite(n)?n:NaN;};
  const dateOf=item=>item.publishedAt||item.publishedDate||item.updatedAt||item.startAt||"";
  const normalizedType=value=>value==="Seminar"?"Seminar":value==="eBook"?"eBook":"Article";
  function contentItems(data){const publications=(data.content||[]).map(item=>({...item,type:normalizedType(item.type)}));const known=new Set(publications.map(item=>item.publicUrl).filter(Boolean));const catalog=(data.publicCatalog||[]).filter(item=>!known.has(item.publicUrl)).map(item=>({...item,type:normalizedType(item.type),status:"Published"}));const seminars=(data.events||[]).map(event=>({id:event.id,type:"Seminar",title:event.title,status:event.lifecycle||"Draft",publicUrl:event.publicUrl,publishedAt:event.publishedAt||event.startAt,updatedAt:event.updatedAt||event.startAt,startAt:event.startAt}));return publications.concat(catalog,seminars);}
  function period(now=Date.now()){const today=dayKey(now),month=today.slice(0,7),week=mondayKey(now),day=Number(today.slice(8)),currentMonthStart=`${month}-01`,previousMonthDate=new Date(`${currentMonthStart}T00:00:00+07:00`);previousMonthDate.setDate(0);const previousMonth=monthKey(previousMonthDate),previousComparableEnd=`${previousMonth}-${String(Math.min(day,new Date(Number(previousMonth.slice(0,4)),Number(previousMonth.slice(5,7)),0).getDate())).padStart(2,"0")}`,lastMonthEnd=new Date(`${currentMonthStart}T00:00:00+07:00`);lastMonthEnd.setDate(0);const lastMonth=monthKey(lastMonthEnd),priorMonthEnd=new Date(`${lastMonth}-01T00:00:00+07:00`);priorMonthEnd.setDate(0);return{today,week,previousWeek:dayKey(new Date(`${week}T00:00:00+07:00`).getTime()-7*DAY),month,currentMonthStart,previousMonth,previousComparableEnd,lastMonth,priorMonth:monthKey(priorMonthEnd)};}
  const published=item=>String(item.status||"").toLowerCase()==="published"||String(item.status||"").toLowerCase()==="completed";
  const countRange=(items,start,end)=>items.filter(item=>published(item)&&dayKey(stamp(dateOf(item)))>=start&&dayKey(stamp(dateOf(item)))<=end).length;
  const delta=(current,previous)=>previous?Math.round((current-previous)/previous*1000)/10:null;
  function dashboard(data,now=Date.now(),filter="All"){
    const p=period(now),all=contentItems(data),items=filter==="All"?all:all.filter(item=>item.type===filter.replace(/s$/,"")||`${item.type}s`===filter),publishedItems=items.filter(published),mtd=countRange(items,p.currentMonthStart,p.today),previousMtd=countRange(items,`${p.previousMonth}-01`,p.previousComparableEnd),thisWeek=countRange(items,p.week,p.today),previousWeekEnd=dayKey(new Date(`${p.week}T00:00:00+07:00`).getTime()-DAY),previousWeek=countRange(items,p.previousWeek,previousWeekEnd),lastMonth=publishedItems.filter(item=>monthKey(stamp(dateOf(item)))===p.lastMonth).length,priorMonth=publishedItems.filter(item=>monthKey(stamp(dateOf(item)))===p.priorMonth).length;
    const latest=publishedItems.slice().sort((a,b)=>stamp(dateOf(b))-stamp(dateOf(a)))[0],attention=items.filter(item=>["Draft","Generated","Validation Required","Failed"].includes(item.status)),upcoming=(data.events||[]).filter(event=>stamp(event.startAt)>now),calendar=all.filter(item=>dateOf(item)).sort((a,b)=>stamp(dateOf(a))-stamp(dateOf(b))).slice(-18),recent=all.filter(item=>dateOf(item)).sort((a,b)=>stamp(dateOf(b))-stamp(dateOf(a))).slice(0,8);
    const weeklyTypes=["Article","eBook"].map(type=>{const typed=all.filter(item=>item.type===type),last=typed.filter(published).sort((a,b)=>stamp(dateOf(b))-stamp(dateOf(a)))[0],count=countRange(typed,p.week,p.today);return{type,count,met:count>=1,lastPublished:last?dateOf(last):"",daysSince:last?Math.max(0,Math.floor((now-stamp(dateOf(last)))/DAY)):null};});
    const insights=[];if(attention.length)insights.push(`${attention.length} content item${attention.length===1?"":"s"} need review or corrective action.`);if(mtd||previousMtd)insights.push(`${mtd} publication${mtd===1?"":"s"} MTD vs ${previousMtd} in the same elapsed period last month.`);weeklyTypes.filter(x=>!x.met).forEach(x=>insights.push(`No ${x.type} has been published this week.`));if(upcoming[0])insights.push(`Next Seminar: ${upcoming.sort((a,b)=>stamp(a.startAt)-stamp(b.startAt))[0].title}.`);
    const months=[...new Set(publishedItems.map(item=>monthKey(stamp(dateOf(item)))))].filter(Boolean).slice(-6).sort();const trend=months.map(month=>({period:month,Article:publishedItems.filter(x=>x.type==="Article"&&monthKey(stamp(dateOf(x)))===month).length,eBook:publishedItems.filter(x=>x.type==="eBook"&&monthKey(stamp(dateOf(x)))===month).length,Seminar:publishedItems.filter(x=>x.type==="Seminar"&&monthKey(stamp(dateOf(x)))===month).length}));
    return{items,summary:{published:publishedItems.length,mtd,drafts:items.filter(x=>x.status==="Draft").length,needsReview:items.filter(x=>["Validation Required","Failed"].includes(x.status)).length,upcoming:upcoming.length},comparison:{wow:{current:thisWeek,previous:previousWeek,delta:delta(thisWeek,previousWeek)},mtd:{current:mtd,previous:previousMtd,delta:delta(mtd,previousMtd)},month:{current:lastMonth,previous:priorMonth,delta:delta(lastMonth,priorMonth)}},latest,attention,calendar,recent,weeklyTypes,insights:insights.slice(0,5),trend};
  }
  function artwork(type,width,height){const rule=RULES[type],ratio=Number(width)/Number(height),valid=!!rule&&Number(width)>0&&Number(height)>0&&Math.abs(ratio-rule.ratio)<=rule.tolerance;return{width:Number(width)||0,height:Number(height)||0,ratio:Number.isFinite(ratio)?ratio:0,requiredRatio:rule?.ratio||0,label:rule?.label||"",valid};}
  function recommendArticle(input={}){const evidence=[input.title,input.subtitle,input.quickSummary,input.source,input.references].filter(Boolean).join(" ").toLowerCase(),tags=(input.tags||[]).map(String),found=needle=>evidence.includes(needle);let primary="",secondary=[],reason="Source evidence is not specific enough for safe automatic classification.",confidence="Low",status="Needs Review";if(["patient","caregiver","public education","masyarakat"].some(found)){primary="Public";reason="The supplied evidence explicitly addresses patients or the public.";confidence="High";status="Recommended";}else if(["diagnosis","treatment","therapy","clinical","surgery","oncology","radiology","pathology"].some(found)){primary="Doctors";reason="The supplied evidence uses clinician-level diagnosis or treatment language.";confidence="Medium";status="Recommended";}else if(["nursing","nurse","pharmacy","pharmacist","allied health"].some(found)){primary="Healthcare Professionals";secondary=found("nurs")?["Nurses"]:found("pharmac")?["Pharmacists"]:["Allied Health Professionals"];reason="The supplied evidence names a professional healthcare audience.";confidence="High";status="Recommended";}const contentType=found("case report")?"Case Report":found("guide")||found("practical")?"Educational Guide":found("study")||found("journal")?"Scientific Article":"Article",inferred=[["thyroid","Thyroid"],["ultrasound","Ultrasonography"],["oncology","Oncology"],["cancer","Cancer"],["surgery","Surgery"],["breast","Breast Cancer"]].filter(([key])=>found(key)).map(([,label])=>label),safeTags=[...new Set(tags.concat(inferred).map(x=>x.trim()).filter(Boolean))].slice(0,8),hashtags=safeTags.slice(0,3).map(tag=>"#"+tag.replace(/[^a-zA-Z0-9]/g,"" )).filter(tag=>tag.length>1);return{primaryAudience:primary,secondaryAudience:secondary,reason,confidence,status,contentType,tags:safeTags,socialKit:{shortCaption:input.title?`${input.title}. Read the source-grounded BA Medicale publication.`:"",longCaption:input.quickSummary?`${input.title}\n\n${input.quickSummary}`:"",hashtags}};}
  return{TZ,RULES,dayKey,monthKey,mondayKey,period,contentItems,dashboard,artwork,recommendArticle};
});
