const test=require('node:test'),assert=require('node:assert/strict'),model=require('../ebooks/model');
test('bookshelf batches 5, 25 and 103 records without duplicates or omissions',()=>{for(const n of [5,25,103]){const books=Array.from({length:n},(_,id)=>({id})),seen=[];for(let i=0;i<Math.ceil(n/25);i++){const b=model.batch(books,i);assert(b.items.length<=25);seen.push(...b.items.map(b=>b.id));}assert.deepEqual(seen,books.map(b=>b.id));assert.equal(model.batch(books,-1).index,0);assert.equal(model.batch(books,999).index,Math.ceil(n/25)-1);}});
test('single cover and desktop spreads preserve page order including odd final spreads',()=>{assert.deepEqual(model.spread(0,4,true),{start:0,end:0});assert.deepEqual(model.spread(2,4,true),{start:1,end:2});assert.deepEqual(model.spread(3,4,true),{start:3,end:3});assert.deepEqual(model.spread(2,4,false),{start:2,end:2});});
test('approved covers win; previews stay neutral and cannot produce search results',()=>{assert.equal(model.cover({}),model.defaultCover);assert.equal(model.cover({cover:'approved.png'}),'approved.png');const demo={demo:true,title:'Example'};assert.equal(model.pages(demo).length,4);assert.deepEqual(model.search(demo,'medical'),[]);});
test('published page text drives both accessible reading and search without fabricated data',()=>{const book={title:'Example',pages:[{title:'Section one',text:'Verified source text'}]};assert.equal(model.pages(book)[1].text,book.pages[0].text);assert.equal(model.search(book,'SOURCE')[0].index,1);assert.deepEqual(model.search(book,''),[]);});

test('an approved visual cover precedes every preserved source PDF page',()=>{const book={title:'Example',cover:'cover.jpg',coverAsPage:true,sourcePages:true,pages:[{title:'Source page 1',text:'Verified source text'}]};const pages=model.pages(book);assert.equal(pages.length,2);assert.equal(pages[0].image,'cover.jpg');assert.equal(pages[0].isCover,true);assert.equal(pages[1],book.pages[0]);});

test('published thyroid book retains nine source pages, tables and searchable text',()=>{const fs=require('node:fs'),crypto=require('node:crypto');const base='assets/ebooks/advanced-diagnostics-and-management-of-thyroid-nodules';const source=JSON.parse(fs.readFileSync(base+'/pages.json','utf8'));const book={sourcePages:true,pages:source.pages};assert.equal(model.pages(book).length,9);assert.deepEqual(source.pages.map(p=>p.image),Array.from({length:9},(_,i)=>base+'/page-'+(i+1)+'.png'));assert.equal(model.search(book,'Category VI')[0].index,5);assert.equal(source.pages.flatMap(p=>p.blocks).filter(b=>b.type==='table').length,3);for(const [file,hash] of [['source.pdf','f4f343127249471198573576b0b2a73b9a4a070001ff0c0a8c0d32e9eff98c7e'],['cover.jpg','318214abe46c3b7cbcef795dafb3bff2815d8879303ceee1cf4b79b441035249']])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(base+'/'+file)).digest('hex'),hash);for(const p of source.pages){assert(fs.existsSync(p.image));const text=p.blocks.map(b=>b.type==='table'?b.rows.flat().join(' '):b.text).join(' ');assert.deepEqual(text.split(/\s+/).filter(Boolean).sort(),p.text.split(/\s+/).filter(Boolean).sort());}});
